Update networking.md
streamnative/snp-cn pull request #11
Opened 2021-12-07 15:06 UTC by infomagic-docs

2021-12-10 04:11 UTC, JipeiWang requested changes

2021-12-10 04:11 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/networking.md
> +title: 配置联网
网络配置

2021-12-10 04:11 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/networking.md
> +- `ClusterIP ` 通过集群的内部 IP 暴露服务。当选择这种类型的服务时，只能通过以下方法在集群内访问服务。
```suggestion
- `ClusterIP ` 通过集群的内部 IP 暴露服务。当选择这种类型的服务时，只能通过以下方法在集群内访问服务：
```

2021-12-10 04:11 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/networking.md
> +**例子**
```suggestion
**示例**
```

2021-12-10 04:11 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/networking.md
>    - ClusterIP + ServicePort
后面的 ServicePort 翻译为服务端口，前后需保持一致

2021-12-10 11:06 UTC, Infomagic-ly commented on v1.2.0/operator-guides/configure/networking.md
> +title: 配置联网
done.

2021-12-10 11:06 UTC, Infomagic-ly commented on v1.2.0/operator-guides/configure/networking.md
> +- `ClusterIP ` 通过集群的内部 IP 暴露服务。当选择这种类型的服务时，只能通过以下方法在集群内访问服务。
done.

2021-12-10 11:07 UTC, Infomagic-ly commented on v1.2.0/operator-guides/configure/networking.md
> +**例子**
done.

2021-12-10 11:08 UTC, Infomagic-ly commented on v1.2.0/operator-guides/configure/networking.md
>    - ClusterIP + ServicePort
done.

2021-12-10 14:25 UTC, tuhaihe requested changes

2021-12-10 14:25 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/networking.md
> +- `LoadBalancer`：客户端使用 Kubernetes 服务商的负载均衡器连接到 Pulsar proxy、Grafana、StreamNative 控制台。
`Kubernetes provider`：不翻译

2021-12-11 04:50 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/networking.md
> +- `LoadBalancer`：客户端使用 Kubernetes 服务商的负载均衡器连接到 Pulsar proxy、Grafana、StreamNative 控制台。
Updated.

2021-12-11 15:28 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2021-12-11 15:28 UTC, merged