Update security-overview.md
streamnative/snp-cn pull request #12
Opened 2021-12-12 12:59 UTC by infomagic-docs

2021-12-12 13:55 UTC, tuhaihe requested changes

2021-12-12 13:55 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/security/security-overview.md
> +- [在负载平衡器上启用 TLS](/operator-guides/configure/security/network-encryption/tls-load-balancer.md)
负责均衡器：请统一下译法。

2021-12-13 02:46 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/security-overview.md
> +- [在负载平衡器上启用 TLS](/operator-guides/configure/security/network-encryption/tls-load-balancer.md)
Fixed

2021-12-13 05:58 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-15 01:36 UTC, merged