Update tls-proxy.md
streamnative/snp-cn pull request #14
Opened 2021-12-13 12:28 UTC by infomagic-docs

2021-12-14 14:25 UTC, tuhaihe requested changes

2021-12-14 14:25 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +Cert-manager 将证书和证书颁发者作为资源类型添加到 Kubernetes 集群中，并简化了获取、更新和使用这些证书的过程。
issuers: 签发者, 貌似更符合常规表达

2021-12-15 01:50 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +Cert-manager 将证书和证书颁发者作为资源类型添加到 Kubernetes 集群中，并简化了获取、更新和使用这些证书的过程。
Updated.

2021-12-15 01:56 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-15 15:45 UTC, JipeiWang requested changes

2021-12-15 15:45 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +- 手动生成证书：由用户生成私钥、公钥和证书颁发机构。
certificate authority 是“证书授权”？机构这个说法不太对吧

2021-12-15 15:45 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +在 StreamNative 平台中，cert-manager 支持从内部签发者和公共签发者授权证书。以下部分介绍了如何使用内部签发者和公共签发者生成证书，然后启用 TLS 加密。
StreamNative Platform 在以前未做翻译，这是产品的名字。

2021-12-15 15:45 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +为 Pulsar 创建 TLS 证书包括创建证书颁发机构（CA）、服务器端证书和客户端证书。
certificate authority (CA) 同上，后文也需要同步更改。

2021-12-15 15:45 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> -4. Answer the prompts.
这句话不太对？

2021-12-15 15:45 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +    - `keystore`：存储证书的文件。Keystore（密钥库）包含证书的私钥，应该保存在一个安全的地方。
密钥库中英文括号内外的位置应该换一下，全文保持一致。后面的信任库也一样。

2021-12-16 00:53 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +- 手动生成证书：由用户生成私钥、公钥和证书颁发机构。
一开始我们也是直译成“证书授权”，后来查了不少资料，“证书颁发机构”应该是比较官方的翻译方式。比如：
https://docs.microsoft.com/zh-cn/windows-server/networking/core-network-guide/cncg/server-certs/install-the-certification-authority
https://docs.aws.amazon.com/zh_cn/zh_cn/acm-pca/latest/userguide/PcaWelcome.html

2021-12-16 00:54 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +在 StreamNative 平台中，cert-manager 支持从内部签发者和公共签发者授权证书。以下部分介绍了如何使用内部签发者和公共签发者生成证书，然后启用 TLS 加密。
Updated

2021-12-16 00:55 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +为 Pulsar 创建 TLS 证书包括创建证书颁发机构（CA）、服务器端证书和客户端证书。
如上恢复，这里的翻译应该没错。

2021-12-16 01:05 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> -4. Answer the prompts.
Updated。这个应该是界面上有一些 prompts，需要用户确认或输入。没有具体信息，不能具体判断是什么情况，目前笼统翻译成“回答提示”了。

2021-12-16 01:08 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +    - `keystore`：存储证书的文件。Keystore（密钥库）包含证书的私钥，应该保存在一个安全的地方。
updated

2021-12-16 03:37 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/security/network-encryption/tls-proxy.md
> +- 手动生成证书：由用户生成私钥、公钥和证书颁发机构。
好的，学习啦

2021-12-16 03:37 UTC, JipeiWang approved these changes

2021-12-16 03:40 UTC, merged