Update kop.md
streamnative/snp-cn pull request #17
Opened 2021-12-15 02:36 UTC by infomagic-docs

2021-12-15 06:47 UTC, tuhaihe requested changes

2021-12-15 06:47 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/kop.md
> +要在 Kubernetes 集群外访问 KoP ，需要安装 [Istio]((https://istio.io/latest/about/service-mesh/)) 并启用 TLS。
`((https://istio.io/latest/about/service-mesh/))` -> 原文错误，此处去掉一层括号，使 Link 生效

2021-12-15 06:47 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/kop.md
> +1. 为 KoP 启用 TLS。详情参见[在 KoP 上启用 TLS](/operator-guides/configure/security/network-encryption/tls-proxy.md#enable-tls-on-kop-with-manuallygenerated-certificates)。
此处链接，请与前面翻译的对应章节做下同步。

2021-12-15 07:33 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/kop.md
> +要在 Kubernetes 集群外访问 KoP ，需要安装 [Istio]((https://istio.io/latest/about/service-mesh/)) 并启用 TLS。
Fixed.

2021-12-15 07:33 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/kop.md
> +1. 为 KoP 启用 TLS。详情参见[在 KoP 上启用 TLS](/operator-guides/configure/security/network-encryption/tls-proxy.md#enable-tls-on-kop-with-manuallygenerated-certificates)。
Updated.

2021-12-15 09:07 UTC, JipeiWang requested changes

2021-12-15 09:07 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/kop.md
> +要在 Kubernetes 集群外访问 KoP ，需要安装 [Istio](https://istio.io/latest/about/service-mesh/) 并启用 TLS。
```suggestion
在 Kubernetes 集群外访问 KoP ，需要安装 [Istio](https://istio.io/latest/about/service-mesh/) 并启用 TLS。
```

2021-12-15 09:07 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/kop.md
> +1. 为 KoP 启用 TLS。详情参见[使用手动生成的证书在 KoP 上启用 TLS](/operator-guides/configure/security/network-encryption/tls-proxy.md#使用手动生成的证书在-KoP-上启用-TLS)。
超链接里面的连字符是否有必要加？

2021-12-15 13:33 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/kop.md
> +1. 为 KoP 启用 TLS。详情参见[使用手动生成的证书在 KoP 上启用 TLS](/operator-guides/configure/security/network-encryption/tls-proxy.md#使用手动生成的证书在-KoP-上启用-TLS)。
查了一下，连字符是需要的，github flavored markdown 里面，section link 会使用标题并把空格变成连字符，大写字母边小写。

2021-12-15 13:37 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/kop.md
> +要在 Kubernetes 集群外访问 KoP ，需要安装 [Istio](https://istio.io/latest/about/service-mesh/) 并启用 TLS。
updated

2021-12-15 13:37 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/kop.md
> +要在 Kubernetes 集群外访问 KoP ，需要安装 [Istio](https://istio.io/latest/about/service-mesh/) 并启用 TLS。
updated

2021-12-15 15:35 UTC, JipeiWang approved these changes

2021-12-16 02:32 UTC, tuhaihe approved these changes

2021-12-16 02:33 UTC, merged