Update backup-restore-metadata-tool.md
streamnative/snp-cn pull request #18
Opened 2021-12-15 07:25 UTC by infomagic-docs

2021-12-15 15:55 UTC, JipeiWang approved these changes

2021-12-16 02:52 UTC, tuhaihe requested changes

2021-12-16 02:52 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/backup-restore-metadata-tool.md
> +# 从旧集群中还原元数据
预览效果中，从本行开始下面都被做了引用处理，需要修订下。

2021-12-16 03:10 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/backup-restore-metadata-tool.md
> +# 从旧集群中还原元数据
Fixed. Thanks.

2021-12-16 03:33 UTC, tuhaihe approved these changes

2021-12-16 03:33 UTC, merged