Update detector.md
streamnative/snp-cn pull request #19
Opened 2021-12-15 14:08 UTC by infomagic-docs

2021-12-15 15:57 UTC, JipeiWang requested changes

2021-12-15 15:57 UTC, JipeiWang commented on v1.2.0/operator-guides/configure/detector.md
> +|pulsar_sla_webservice_up| 标尺 | Webservice 是否正在运行。值 `1` 表示网络服务正在运行。值 `0` 表示 webservice 没有运行。|
webservice 前后翻译需同步

2021-12-16 00:40 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/detector.md
> +|pulsar_sla_webservice_up| 标尺 | Webservice 是否正在运行。值 `1` 表示网络服务正在运行。值 `0` 表示 webservice 没有运行。|
Updated.

2021-12-16 03:38 UTC, JipeiWang approved these changes

2021-12-17 13:35 UTC, tuhaihe requested changes

2021-12-17 13:35 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/detector.md
> +Pulsar 侦查器监控 Pulsar 集群的健康状况。当需要监控某个集群或跨集群从消息发送到消息被消费的分布延迟，就可以使用 Pulsar 侦查器。Pulsar 侦查器能够轻松地与现有的侦查工具（如 Prometheus）集成，并在 Grafana 中查看关键指标。
existing monitoring tools : 监控工具。翻译成侦查有点别扭，前者更常用。

2021-12-17 13:35 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/detector.md
> +Pulsar 侦查器监控 Pulsar 集群的健康状况。当需要监控某个集群或跨集群从消息发送到消息被消费的分布延迟，就可以使用 Pulsar 侦查器。Pulsar 侦查器能够轻松地与现有的侦查工具（如 Prometheus）集成，并在 Grafana 中查看关键指标。
distribution latency：从上下文来看，应该是“分发延迟”。distribution 可做分发、分布，分布指的的排列，不太符合原文意思，请更新。下同。

2021-12-17 13:40 UTC, tuhaihe requested changes

2021-12-17 13:40 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/detector.md
>  ![](../image/pulsar-detector.png)
图片未显示，帮忙更新下图片地址吧，原文有错。

2021-12-17 14:52 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/detector.md
> +Pulsar 侦查器监控 Pulsar 集群的健康状况。当需要监控某个集群或跨集群从消息发送到消息被消费的分布延迟，就可以使用 Pulsar 侦查器。Pulsar 侦查器能够轻松地与现有的侦查工具（如 Prometheus）集成，并在 Grafana 中查看关键指标。
Updated.

2021-12-17 14:53 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/detector.md
>  ![](../image/pulsar-detector.png)
Fixed.

2021-12-19 03:28 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-19 03:28 UTC, merged