Update grafana.md
streamnative/snp-cn pull request #21
Opened 2021-12-16 03:59 UTC by infomagic-docs

2021-12-16 06:17 UTC, tuhaihe requested changes

2021-12-16 06:17 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/monitoring/grafana.md
> -StreamNative Platform supports exposing the Grafana service using the [LoadBalancer](/operator-guides/configure/networking.md#loadbalancer) or [NodePort](/operator-guides/configure/networking.md#node
文件链接地址，更新成最新翻译章节名称。

2021-12-16 06:19 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/monitoring/grafana.md
> -StreamNative Platform supports exposing the Grafana service using the [LoadBalancer](/operator-guides/configure/networking.md#loadbalancer) or [NodePort](/operator-guides/configure/networking.md#node
这个我们也看到了，原文也并没有这两个章节，应该是原文错误，并不存在这两个章节。

2021-12-16 06:32 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/monitoring/grafana.md
> -StreamNative Platform supports exposing the Grafana service using the [LoadBalancer](/operator-guides/configure/networking.md#loadbalancer) or [NodePort](/operator-guides/configure/networking.md#node
那更新到 networking.md 这个文件层级吧，后面小章节直接去掉吧

2021-12-16 06:40 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/monitoring/grafana.md
> -StreamNative Platform supports exposing the Grafana service using the [LoadBalancer](/operator-guides/configure/networking.md#loadbalancer) or [NodePort](/operator-guides/configure/networking.md#node
已更新。不过这个好像不影响，还是会跳到networking 文件。

2021-12-16 09:08 UTC, JipeiWang approved these changes

2021-12-17 03:21 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-17 03:21 UTC, merged