Update alertmanager.md
streamnative/snp-cn pull request #22
Opened 2021-12-16 04:23 UTC by infomagic-docs

2021-12-16 06:30 UTC, tuhaihe requested changes

2021-12-16 06:30 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +如下示例显示了如何用 ZooKeeper 配置告警规则。
为 ZooKeeper 配置规则，不是用 ZooKeeper 配置。

2021-12-16 06:30 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +告警规则允许你根据表达式（ Prometheus 表达式语言）定义告警条件，并将有关触发告警的通知发送到外部服务。一旦告警表达式在给定时间点产生一个或多个向量元素时，告警就将为这些元素标签集激活。
「告警就将为这些元素标签集激活。」-可优化译法，有点别扭

2021-12-16 06:30 UTC, tuhaihe commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +默认情况下，Alertmanager 与 StreamNative Platform 一起启用。 如果要禁用 Alertmanager，你可以在 Pulsar 集群的 YAML 配置文件中设置 `monitoring.alert_manager: false`。
「Alertmanager 与 StreamNative Platform 一起启用」按表面翻译没问题，就是不地道，意思是Alertmanager 作为 Paltform 一个组件，默认就启用了 ── 优化译法。

2021-12-16 06:42 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +如下示例显示了如何用 ZooKeeper 配置告警规则。
Updated.

2021-12-16 06:45 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +告警规则允许你根据表达式（ Prometheus 表达式语言）定义告警条件，并将有关触发告警的通知发送到外部服务。一旦告警表达式在给定时间点产生一个或多个向量元素时，告警就将为这些元素标签集激活。
更新了一个版本，上下文比较少，不是很好理解。

2021-12-16 06:47 UTC, infomagic-docs commented on v1.2.0/operator-guides/configure/monitoring/alertmanager.md
> +默认情况下，Alertmanager 与 StreamNative Platform 一起启用。 如果要禁用 Alertmanager，你可以在 Pulsar 集群的 YAML 配置文件中设置 `monitoring.alert_manager: false`。
Updated.

2021-12-16 09:16 UTC, JipeiWang approved these changes

2021-12-17 03:23 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-17 03:23 UTC, merged