Update sn-deploy.md
streamnative/snp-cn pull request #25
Opened 2021-12-16 08:35 UTC by infomagic-docs

2021-12-18 04:25 UTC, tuhaihe requested changes

2021-12-18 04:25 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +## 在互联网条件下安装 StreamNative Platform
在互联网条件下：可优化译法，有点生硬，可：在联网条件下  <- 比较易懂；
后面无网环境相关翻译，也请更新：离线

2021-12-18 04:25 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts /pulsar-io-concepts.md)，以支持流处理应用
/concepts /pulsar-io-concepts.md：请更新；

2021-12-18 04:25 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +6. 安装 FunctionMesh operator。
FunctionMesh：我们分开写，下同

2021-12-18 04:25 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts /pulsar-io-concepts.md)，以支持流处理应用
(/concepts /pulsar-io-concepts.md)：请更新

2021-12-18 04:25 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +> 在无互联网条件下安装 StreamNative Platform ，需要预加载所需的 Docker 镜像。预加载 Docker 镜像的方法请参见[预加载 Docker 镜像](/operator-guides/sn-plan.md#preload-docker-images)。
/operator-guides/sn-plan.md#preload-docker-images：请与之前节点翻译保持最新 ； 后面请多多注意，类似情况请自行更新~

2021-12-18 07:30 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +## 在互联网条件下安装 StreamNative Platform
Updated.

2021-12-18 07:31 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +6. 安装 FunctionMesh operator。
updated

2021-12-18 07:32 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts /pulsar-io-concepts.md)，以支持流处理应用
Fixed. Thanks.

2021-12-18 07:33 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts /pulsar-io-concepts.md)，以支持流处理应用
Updated.

2021-12-18 07:39 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +> 在无互联网条件下安装 StreamNative Platform ，需要预加载所需的 Docker 镜像。预加载 Docker 镜像的方法请参见[预加载 Docker 镜像](/operator-guides/sn-plan.md#preload-docker-images)。
Updated. 收到，这个 section 引用的更新确实比较容易忽略。

2021-12-19 03:35 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 16:29 UTC, JipeiWang requested changes

2021-12-20 16:29 UTC, JipeiWang commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程
```suggestion
   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Function](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程序。
```

2021-12-20 16:29 UTC, JipeiWang commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程
```suggestion
   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Function](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程序。
```

2021-12-21 02:57 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程
+1，指代单个 Function 时用单数, @infomagic-docs 请更新成单数

2021-12-22 05:14 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程
Updated.

2021-12-22 05:14 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/sn-deploy.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 作为无服务器（Serverless）框架，协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)，以支持流处理应用程
Updated.

2021-12-22 14:34 UTC, merged