Update deploy-snp-aws.md
streamnative/snp-cn pull request #26
Opened 2021-12-16 10:06 UTC by infomagic-docs

2021-12-18 04:50 UTC, tuhaihe requested changes

2021-12-18 04:50 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +1. 定义一个 EKS 集群配置文件，用于部署预定义的 StreamNative Platform。
此处翻译待优化，意思弄反了？

2021-12-18 09:24 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +1. 定义一个 EKS 集群配置文件，用于部署预定义的 StreamNative Platform。
应该没有弄反，看了下 example 的文件，就是一个创建 cluster 的配置文件，感觉目前的翻译通顺点。
是否希望改成：

- 定义一个 EKS 集群配置文件，包含预定义的 StreamNative Platform。
或
- 使用预定义的 StreamNative Platform 来定义一个 EKS 集群配置文件。

直译的话就是后一个。
或者把“预定义”改成“预设”？请反馈。

2021-12-19 03:24 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +1. 定义一个 EKS 集群配置文件，用于部署预定义的 StreamNative Platform。
了解，第一个更好一些。做 EKS 集群的时候，也包括了 StreamNative Platform 配置。

2021-12-19 10:19 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +1. 定义一个 EKS 集群配置文件，用于部署预定义的 StreamNative Platform。
Updated.

2021-12-20 15:34 UTC, JipeiWang requested changes

2021-12-20 15:34 UTC, JipeiWang commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +title: 在 AWS 上部署 StreamNative 平台
StreamNative Platform 不做翻译，请通篇确认。

2021-12-20 15:34 UTC, JipeiWang commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +   - 验证 BookKeeper Controller Manager、Pulsar Controller Manager、ZooKeeper Controller Manager 和 Vault Controller Manager 是否正常运行。
原文后面几个是 Manage，我再和作者确认一下。

2021-12-21 02:01 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +title: 在 AWS 上部署 StreamNative 平台
Updated。已通篇确认，就这个漏了。

2021-12-21 02:02 UTC, infomagic-docs commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +   - 验证 BookKeeper Controller Manager、Pulsar Controller Manager、ZooKeeper Controller Manager 和 Vault Controller Manager 是否正常运行。
应该是原文错误。下面的代码里也是manager：
pulsar-operator-bookkeeper-controller-manager-d5d7b4668-q256l   1/1     Running   0          30h
pulsar-operator-pulsar-controller-manager-8f7fd4569-6jh2p       1/1     Running   0          30h
pulsar-operator-zookeeper-controller-manager-6cff55bfb7-bngtf

2021-12-21 13:55 UTC, tuhaihe approved these changes

2021-12-21 13:56 UTC, tuhaihe commented on v1.2.0/operator-guides/deploy/deploy-snp-aws.md
> +   - 验证 BookKeeper Controller Manager、Pulsar Controller Manager、ZooKeeper Controller Manager 和 Vault Controller Manager 是否正常运行。
从代码和逻辑上来看是 Manager 比较恰当。

2021-12-22 01:33 UTC, merged