Update sn-monitor.md
streamnative/snp-cn pull request #29
Opened 2021-12-17 02:29 UTC by infomagic-docs

2021-12-18 05:21 UTC, tuhaihe requested changes

2021-12-18 05:21 UTC, tuhaihe commented on v1.2.0/operator-guides/sn-monitor.md
> +StreamNative Platform 支持[暴露 Grafana 服务](/operator-guides/configure/monitoring/grafana.md#expose-grafana-service)。可以通过以下 URL 访问 Grafana 仪表板。
(/operator-guides/configure/monitoring/grafana.md#expose-grafana-service) : 地址请与已翻译章节标题对应

2021-12-18 07:21 UTC, infomagic-docs commented on v1.2.0/operator-guides/sn-monitor.md
> +StreamNative Platform 支持[暴露 Grafana 服务](/operator-guides/configure/monitoring/grafana.md#expose-grafana-service)。可以通过以下 URL 访问 Grafana 仪表板。
好的。Updated.

2021-12-19 03:09 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 14:53 UTC, JipeiWang approved these changes

2021-12-21 02:16 UTC, merged