translate the overview page
streamnative/snp-cn pull request #3
Opened 2021-11-18 08:08 UTC by infomagic-docs

2021-11-18 13:30 UTC, tuhaihe requested changes

2021-11-18 13:30 UTC, tuhaihe commented on v1.2.0/overview.md
> +作为一个云原生批流融合数据平台，StreamNative Platform 可以帮助你为实时和历史事件创建实时应用程序和数据基础架构。[StreamNative](https://streamnative.io/) 由 [Apache Pulsar](https://pulsar.apache.org/en/) 和 [Apache BookKeeper](https://bookkeeper.a
1. `原始团队` -> `创始团队` ， 我们常用后者表达
2. `以提供丰富的客户体验和由数据驱动的业务`，可再优化下译法

2021-11-18 13:30 UTC, tuhaihe commented on v1.2.0/overview.md
> +|监控堆栈：集成仪表板及 Pulsar 警报规则（基于 Prometheus/Grafana/Alertmanager）|    | √   |
1. `警报` -> `告警`，后者在运维中常用
2.

2021-11-18 13:30 UTC, tuhaihe commented on v1.2.0/overview.md
> +    Pulsar proxy 是一个可选网关，运行在 Pulsar 集群的 broker 之前。
`运行在 Pulsar 集群的 broker 之前。`可再优化下译法，目前感觉怪怪的

2021-11-18 13:30 UTC, tuhaihe commented on v1.2.0/overview.md
> +StreamNative Platform 的核心是 [Apache Pulsar](https://pulsar.apache.org)，一个开源的分布式云原生批流融合数据平台。
`messaging and streaming platform.`-> 针对 Pulsar 而言，可以译为 `消息流平台`。

2021-11-18 13:30 UTC, tuhaihe commented on v1.2.0/overview.md
> +在 Apache Pulsar 的支持下，StreamNative Platform 将不同来源的数据整合到公司统一的批流融合数据平台中，从而可以轻松创建关键性任务消息和流应用以及实时数据通道。 StreamNative Platform 让你可以专注于如何从实时数据中最大化业务价值，而无需担心底层机制，比如数据如何在各个系统之间传递，以及如何可靠地存储数据以供处理。
`在 Apache Pulsar 的支持下`再优化译法，目前令人感觉是Pulsar的主动行为，要体现基于Apache Pulsar、借助 Apache Pulsar 这种感觉，会更加自然。

2021-11-18 19:54 UTC, JipeiWang commented on v1.2.0/overview.md
> +- [为什么要使用 StreamNative Platform？](#为什么要使用-streamnative-platform)
```suggestion
- [为什么选择 StreamNative Platform？](#为什么选择-streamnative-platform)
```

2021-11-18 20:15 UTC, JipeiWang requested changes

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +作为一个云原生批流融合数据平台，StreamNative Platform 可以帮助你为实时和历史事件创建实时应用程序和数据基础架构。[StreamNative](https://streamnative.io/) 由 [Apache Pulsar](https://pulsar.apache.org/en/) 和 [Apache BookKeeper](https://bookkeeper.a
```suggestion
作为一个云原生批流融合数据平台，StreamNative Platform 可以帮助你为实时和历史事件创建实时应用程序和数据基础架构。[StreamNative](https://streamnative.io/) 由 [Apache Pulsar](https://pulsar.apache.org/en/) 和 [Apache BookKeeper](https://bookkeeper.apache.org/) 的原始团队打造，提供了一个完整的、可自我管理的平台。StreamNative Platform 提供丰富的顾客体验，可在整个组织中持续流转数据，支撑由数据驱动的业务。用户可以选择将 StreamNative Platform 部署在本地或云端。
```

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +在 Apache Pulsar 的支持下，StreamNative Platform 将不同来源的数据整合到公司统一的批流融合数据平台中，从而可以轻松创建关键性任务消息和流应用以及实时数据通道。 StreamNative Platform 让你可以专注于如何从实时数据中最大化业务价值，而无需担心底层机制，比如数据如何在各个系统之间传递，以及如何可靠地存储数据以供处理。
```suggestion
借助 Apache Pulsar，StreamNative Platform 将不同来源的数据整合到公司统一的批流融合数据平台中，从而可以轻松创建关键性任务消息、流应用与实时数据通道。 StreamNative Platform 让你可以专注于从实时数据中最大化业务价值，而无需担心底层机制上数据如何在各个系统之间传递，以及如何可靠地存储数据以供处理等问题。
```

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +# 为什么要使用 StreamNative Platform？
```suggestion
# 为什么选择 StreamNative Platform？
```

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> -- **Committer-driven expertise**: Leverage the rich experience of Pulsar experts and committers to support you throughout the application development lifecycle.
committer 不做翻译

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +- **生产阶段**：在生产中实现具有企业级功能的事件流。
```suggestion
- **企业级生产**：在生产中实现具有企业级功能的事件流。
```
感觉这里不需要完全按照英文，这里想表达的是特性好处，生产阶段并不是形容词

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +Apache Pulsar 已经得到许多[主流技术公司](https://pulsar.apache.org/en/powered-by/)的全球采用，如 Verizon Media、Narvar、Overstock、Nutanix、Yahoo！JAPAN、腾讯、OVHCloud 和Clever Cloud 等，Apache Pulsar 为这些公司提供在性能、可扩展性和弹性方面的能力。Puls
```suggestion
Apache Pulsar 已经得到许多全球[主流技术公司](https://pulsar.apache.org/en/powered-by/)的采用，如 Verizon Media、Narvar、Overstock、Nutanix、Yahoo！JAPAN、腾讯、OVHCloud 和 Clever Cloud 等，Apache Pulsar 为这些公司提供其在性能、可扩展性和弹性方面的能力。Pulsar 的普及是市场对实时数据支持技术不断增长的需求所推动的，这些需求包括异步应用程序、核心业务应用程序以及 ETL 等。
```

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +StreamNative Platform 的每个版本都包含最新版本的 Pulsar，以及额外的工具和服务。这些工具和服务让创建和管理云原生批流融合数据平台变得更加简单。StreamNative Platform 同时包含了社区版和商业版的功能，可以很好地补充和加强你的 Pulsar 部署。
```suggestion
StreamNative Platform 的每个版本都包含最新版本的 Pulsar 的全部功能与特性，并包含 StreamNative 额外的工具和服务。这些工具和服务让创建和管理云原生批流融合平台变得更加简单。StreamNative Platform 同时包含了社区版和商业版的功能，可以很好地补充并加强你的 Pulsar 部署。
```

2021-11-18 20:15 UTC, JipeiWang commented on v1.2.0/overview.md
> +下表对比了 Apache Pulsar 和 StreamNative Platform 所支持的功能。
```suggestion
下表为 Apache Pulsar 和 StreamNative Platform 功能对比。
```

2021-11-19 07:26 UTC, infomagic-docs commented on v1.2.0/overview.md
> +作为一个云原生批流融合数据平台，StreamNative Platform 可以帮助你为实时和历史事件创建实时应用程序和数据基础架构。[StreamNative](https://streamnative.io/) 由 [Apache Pulsar](https://pulsar.apache.org/en/) 和 [Apache BookKeeper](https://bookkeeper.a
updated

2021-11-19 07:27 UTC, infomagic-docs commented on v1.2.0/overview.md
> +|监控堆栈：集成仪表板及 Pulsar 警报规则（基于 Prometheus/Grafana/Alertmanager）|    | √   |
updated

2021-11-19 07:37 UTC, infomagic-docs commented on v1.2.0/overview.md
> +StreamNative Platform 的核心是 [Apache Pulsar](https://pulsar.apache.org)，一个开源的分布式云原生批流融合数据平台。
updated

2021-11-19 07:38 UTC, infomagic-docs commented on v1.2.0/overview.md
> +在 Apache Pulsar 的支持下，StreamNative Platform 将不同来源的数据整合到公司统一的批流融合数据平台中，从而可以轻松创建关键性任务消息和流应用以及实时数据通道。 StreamNative Platform 让你可以专注于如何从实时数据中最大化业务价值，而无需担心底层机制，比如数据如何在各个系统之间传递，以及如何可靠地存储数据以供处理。
updated based on Jipei's suggestion.

2021-11-19 07:41 UTC, infomagic-docs commented on v1.2.0/overview.md
> -- **Committer-driven expertise**: Leverage the rich experience of Pulsar experts and committers to support you throughout the application development lifecycle.
updated

2021-11-19 07:43 UTC, infomagic-docs commented on v1.2.0/overview.md
> +    Pulsar proxy 是一个可选网关，运行在 Pulsar 集群的 broker 之前。
updated

2021-11-19 07:49 UTC, JipeiWang approved these changes

2021-11-19 08:11 UTC, tuhaihe approved these changes
@tuhaihe Approve this PR.

2021-11-19 08:11 UTC, merged