Update sn-upgrade.md
streamnative/snp-cn pull request #30
Opened 2021-12-17 02:41 UTC by infomagic-docs

2021-12-18 05:25 UTC, tuhaihe requested changes

2021-12-18 05:25 UTC, tuhaihe commented on v1.2.0/operator-guides/upgrade/sn-upgrade.md
> +# 在互联网条件下升级 StreamNative Platform
翻译改进建议，同前。

2021-12-18 05:25 UTC, tuhaihe commented on v1.2.0/operator-guides/upgrade/sn-upgrade.md
> +# 在无互联网条件下升级 StreamNative Platform
翻译改进建议，同前。

2021-12-18 09:08 UTC, infomagic-docs commented on v1.2.0/operator-guides/upgrade/sn-upgrade.md
> +# 在互联网条件下升级 StreamNative Platform
Updated.

2021-12-18 09:08 UTC, infomagic-docs commented on v1.2.0/operator-guides/upgrade/sn-upgrade.md
> +# 在无互联网条件下升级 StreamNative Platform
Updated

2021-12-19 03:08 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 14:49 UTC, JipeiWang approved these changes

2021-12-21 02:15 UTC, merged