Update connect-pulsar-client.md
streamnative/snp-cn pull request #34
Opened 2021-12-17 03:26 UTC by infomagic-docs

2021-12-17 03:28 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +按照[准备连接 Pulsar 集群](/user-guides/connect/connect-pulsar-cluster/connect-prepare.md)中的描述设置 `--url` 和 `--auth-params` 参数。
该引用文档似乎并没有介绍这两个参数？目标connect-prepare.md原文是否有问题？

2021-12-18 06:59 UTC, tuhaihe requested changes

2021-12-18 06:59 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +`pulsar-client` 是一个 CLI（命令行工具），用于在 pulsar 主题中生产和消费消息。
注意术语大小写

2021-12-18 06:59 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +按照[准备连接 Pulsar 集群](/user-guides/connect/connect-pulsar-cluster/connect-prepare.md)中的描述设置 `--url` 和 `--auth-params` 参数。
可先忽略这个问题。

2021-12-18 07:16 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +按照[准备连接 Pulsar 集群](/user-guides/connect/connect-pulsar-cluster/connect-prepare.md)中的描述设置 `--url` 和 `--auth-params` 参数。
OK.

2021-12-18 07:16 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +`pulsar-client` 是一个 CLI（命令行工具），用于在 pulsar 主题中生产和消费消息。
Updated.

2021-12-19 03:05 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 14:16 UTC, JipeiWang requested changes

2021-12-20 14:16 UTC, JipeiWang commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +`pulsar-client` 是一个 CLI（命令行工具），用于在 Pulsar 主题中生产和消费消息。
```suggestion
`pulsar-client` 是一个 CLI（命令行界面）工具，用于在 Pulsar 主题中生产和消费消息。
```

2021-12-20 14:16 UTC, JipeiWang commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +title: 使用 pulsar-client CLI 连接到 Pulsar 集群
```suggestion
title: 使用 pulsar-client CLI 工具连接到 Pulsar 集群
```

2021-12-20 14:16 UTC, JipeiWang commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +如下示例显示了如何使用 pulsar-client CLI（命令行工具）连接到 Pulsar 集群，并为 `test-topic` 主题生成 10 条消息。
同上

2021-12-21 02:34 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +`pulsar-client` 是一个 CLI（命令行工具），用于在 Pulsar 主题中生产和消费消息。
差别不大，保持当前翻译吧；日常用于就是`命令行工具`

2021-12-21 02:35 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/cli-tools/connect-pulsar-client.md
> +title: 使用 pulsar-client CLI 连接到 Pulsar 集群
可不改，保持当前翻译

2021-12-21 02:35 UTC, merged