Update pulsar client topics
streamnative/snp-cn pull request #35
Opened 2021-12-17 04:04 UTC by infomagic-docs

2021-12-17 04:06 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +3. 创建 Node.js 生产者并使用 Java 生产者来生产消息。
此处the Java producer是否为原文错误？是否需要改成 Node.js producer? 请确认。

2021-12-17 04:07 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +2. 创建 Node.js 消费者并使用 Java 消费者来消费消息。
此处the Java consumer 是否为原文错误？是否需要改成 Node.js consumer ? 请确认。

2021-12-18 07:56 UTC, tuhaihe requested changes

2021-12-18 07:56 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +2. 创建 Node.js 消费者并使用 Java 消费者来消费消息。
👍 请做下修改，原文错误

2021-12-18 07:56 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +3. 创建 Node.js 生产者并使用 Java 生产者来生产消息。
请做下修改 👍

2021-12-18 07:56 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-java.md
> +title: 使用 Java 客户端连接 Pulsar 集群
本章节样式显示有错乱，请修复下。

2021-12-18 07:56 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-go.md
> +2. 创建 Go 消费者并使用 Go 消费者来消费消息。
样式错乱，请修复

2021-12-18 08:55 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +3. 创建 Node.js 生产者并使用 Java 生产者来生产消息。
Updated.

2021-12-18 08:55 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-nodejs.md
> +2. 创建 Node.js 消费者并使用 Java 消费者来消费消息。
Updated.

2021-12-18 09:03 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-go.md
> +2. 创建 Go 消费者并使用 Go 消费者来消费消息。
Fixed.

2021-12-18 09:03 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-java.md
> +title: 使用 Java 客户端连接 Pulsar 集群
Fixed.

2021-12-19 03:04 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 13:38 UTC, JipeiWang requested changes

2021-12-20 13:38 UTC, JipeiWang commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-websocket.md
> +本示例介绍了如何使用 WebSocket API 客户端连接到 Pulsar 集群，然后向 Pulsar 集群生产和从 Pulsar 集群消费消息。
这个应该不是“客户端”

2021-12-21 02:47 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-websocket.md
> +本示例介绍了如何使用 WebSocket API 客户端连接到 Pulsar 集群，然后向 Pulsar 集群生产和从 Pulsar 集群消费消息。
@infomagic-docs 可去掉 `客户端`

2021-12-22 03:44 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/pulsar-clients/connect-websocket.md
> +本示例介绍了如何使用 WebSocket API 客户端连接到 Pulsar 集群，然后向 Pulsar 集群生产和从 Pulsar 集群消费消息。
Updated.

2021-12-22 04:12 UTC, tuhaihe approved these changes

2021-12-22 04:12 UTC, merged