Update connect-kafka-java.md
streamnative/snp-cn pull request #36
Opened 2021-12-17 07:06 UTC by infomagic-docs

2021-12-17 07:08 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> -2. Configure [KoP SSL connection](/operator-guides/sn-plan.md#generate-ssl-key-and-certificates-for-KoP) and enable KoP.
原文/operator-guides/sn-plan.md，并没有 KoP ssl的步骤，应该是原文错误。译文已修改，请确认。

2021-12-17 07:08 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> -- Install Istio. For details, see [install Istio for KoP access](/operator-guides/sn-plan.md#install-istio-for-kop-access).
原文/operator-guides/sn-plan.md，并没有 Istio 的内容，应该是原文错误。已主动更新译文连接，请确认连接是否正确。

2021-12-18 08:03 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> -- Install Istio. For details, see [install Istio for KoP access](/operator-guides/sn-plan.md#install-istio-for-kop-access).
确认，感谢修复 👍

2021-12-18 08:04 UTC, tuhaihe commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> -2. Configure [KoP SSL connection](/operator-guides/sn-plan.md#generate-ssl-key-and-certificates-for-KoP) and enable KoP.
确认👍

2021-12-18 08:09 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 14:19 UTC, JipeiWang requested changes

2021-12-20 14:19 UTC, JipeiWang commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> +- 安装 Istio。详情参见[安装 Istio 以实现 KoP 访问](/operator-guides/configure/kop.md##安装-istio-以实现-kop-访问)。
多了一个 #

2021-12-22 03:41 UTC, infomagic-docs commented on v1.2.0/user-guides/connect/connect-pulsar-cluster/kafka-clients/connect-kafka-java.md
> +- 安装 Istio。详情参见[安装 Istio 以实现 KoP 访问](/operator-guides/configure/kop.md##安装-istio-以实现-kop-访问)。
Fixed. Thanks.

2021-12-22 04:14 UTC, merged