Update login-console.md
streamnative/snp-cn pull request #37
Opened 2021-12-17 07:43 UTC by infomagic-docs

2021-12-17 07:45 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/login-console.md
> +3. 点击**用谷歌登录**。
给到我们的是 SN cloud 的环境界面，登录页面没有 Google 选项，因此不确定翻译是否和真实 UI 一致。

2021-12-17 15:02 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/login-console.md
> -   ![](../../image/log-in-console.png)
原文图片链接应该是有误，无法显示，译文更新了。

2021-12-18 08:13 UTC, tuhaihe commented on v1.2.0/user-guides/admin/login-console.md
> +StreamNative 控制台是基于 Web 的 GUI 管理和监控工具，可帮助 Pulsar 用户管理租户、命名空间、主题、订阅等。
GUI: 图形 <- 我们直接点就行

2021-12-18 08:19 UTC, tuhaihe commented on v1.2.0/user-guides/admin/login-console.md
> -   ![](../../image/log-in-console.png)
感谢 👍

2021-12-18 08:21 UTC, tuhaihe commented on v1.2.0/user-guides/admin/login-console.md
> +3. 点击**用谷歌登录**。
可先按此翻译

2021-12-18 08:23 UTC, tuhaihe requested changes

2021-12-18 08:23 UTC, tuhaihe commented on v1.2.0/user-guides/admin/login-console.md
> +StreamNative 控制台是基于 Web 的 GUI 管理和监控工具，可帮助 Pulsar 用户管理租户、命名空间、主题、订阅等。
GUI<- 我们直接点就行，`图形界面` 之类

2021-12-18 08:52 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/login-console.md
> +StreamNative 控制台是基于 Web 的 GUI 管理和监控工具，可帮助 Pulsar 用户管理租户、命名空间、主题、订阅等。
Updated.

2021-12-19 02:59 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 13:33 UTC, JipeiWang requested changes

2021-12-20 13:33 UTC, JipeiWang commented on v1.2.0/user-guides/admin/login-console.md
> +然后，你将看到 StreamNative 控制台 GUI，并且可以管理以下资源：
GUI 的翻译前后需保持一致

2021-12-22 03:39 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/login-console.md
> +然后，你将看到 StreamNative 控制台 GUI，并且可以管理以下资源：
Updated. Thanks.

2021-12-22 04:13 UTC, merged