Update work-with-service-accounts.md
streamnative/snp-cn pull request #38
Opened 2021-12-17 08:11 UTC by infomagic-docs

2021-12-18 08:36 UTC, tuhaihe requested changes

2021-12-18 08:36 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-service-accounts.md
>     ![](../../image/create-service-account.png)
请更新图片位置，下同。未正常显示。

2021-12-18 08:49 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-service-accounts.md
>     ![](../../image/create-service-account.png)
Updated.

2021-12-19 02:45 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-20 13:28 UTC, JipeiWang approved these changes

2021-12-21 02:50 UTC, merged