Update quickstart.md
streamnative/snp-cn pull request #4
Opened 2021-11-23 08:10 UTC by infomagic-docs

2021-11-23 10:44 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   在安装 cert-manager 时，需要在 Helm 安装命令中添加 `--set installCRDs=true` 标志，从而将 cert-manager 所需的 CRD 资源一并安装到集群中。
flag 翻译为 `参数` 更为常用

2021-11-23 17:51 UTC, JipeiWang commented
目前看了第一个文档。剩下的我还是先等重新提 PR 再 review 吧。

2021-11-24 01:12 UTC, tuhaihe requested changes

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +6. 安装 FunctionMesh operator。
`FunctionMesh` -> `Function Mesh`，原文有误，需要中间加空格，下面也一同帮助更新吧。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 是一个无服务器（Serverless）框架，用于协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)的流处理应用程
`用于协调多个Pulsar Functions  和  Pulsar IO 连接器的流处理应用程序。` 可再优化下，协调的不是流处理应用程序。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +        helm install -f /path/to/pulsar-cluster/file.yaml $RELEASE_NAME streamnative/SN-platform --set initialize=true
命令不要改动

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> -    pulsarctl tenants create TENANT_NAME
原文步骤 2 与第 1 步操作重复，删除。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +通过  Kafka on Pulsar (KoP) ， StreamNative Platform 中的 Pulsar brokers 支持原生的 Kafka 协议。因此，无需修改代码，就可以将现有的 Kafka 应用程序和服务迁移到 Apache Pulsar 上。
brokers，注意中文下的单复数转换。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +通过  Kafka on Pulsar (KoP) ， StreamNative Platform 中的 Pulsar brokers 支持原生的 Kafka 协议。因此，无需修改代码，就可以将现有的 Kafka 应用程序和服务迁移到 Apache Pulsar 上。
`StreamNative Platform 中的 Pulsar brokers 支持原生的 Kafka 协议。` -> `StreamNative Platform 中的 Pulsar broker 就可以支持原生的 Kafka 协议。`  
 Tip：适当时候加下连词，保持中文翻译的连贯。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +    | `username`| Kafka 客户端连接到 Pulsar 集群的用户名。设置为存储 Kafka 主题的 Pulsar 租户和命名空间（`TENANT_NAME/NAMESPACE_NAME`）的名称。 | `public/default` |
`设置为存储 Kafka 主题的 Pulsar 租户和命名空间（`TENANT_NAME/NAMESPACE_NAME`）的名称。`请优化下翻译~

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +在完成[步骤 3 ](#step-3 use-pulsar-client-to-produce and-consume-events)和[步骤 4 ](#step-4 use-kafka-client-to-produce and-consume-events)后，Pulsar 生产者、Pulsar 消费者、Kafka 生产者和 Kafka 消费者都可正常运行。Pulsar 消费者可以从Puls
请再确认下 Step 3\Step 4 的链接是否OK

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +        * Pulsar 消费者
`Pulsar 消费者`->`Pulsar 消费者端`，下面一样，请做下更新

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   * Pulsar 消费者
同上类似。

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   * Kafka 消费者
同上类似

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +StreamNative 控制台是基于 Web 的图形化界面（GUI）管理工具，用于管理和监控 Pulsar 。
`Pulsar 。`句号前空格请删除，其他也一并做下检查吧

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   3. 为命名空间输入一个名称，然后点击**确定**。名称空间的名称最多包含 40 个字符，支持小写字母（a-z），数字字符（0-9），以及特殊字符连字符（-）。
`名称空间`更新下翻译

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +    `sn-grafana` 已暴露，其外部 IP 是`{GRAFANA-EXTERNAL-IP}`。
此处是终端输出信息，不需要翻译

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +    `sn-prometheus` 已暴露，其外部 IP 是 `{PROM-EXTERNAL-IP}`。
此处是终端输出信息，不需要翻译

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +   现在你可以用 Grafana 仪表板查看组件的详细指标了，如 bookie、JVM、消息、节点、代理、Zookeeper、pulsar 主题等。
`Zookeeper` -> `ZooKeeper` 
`pulsar` -> `Pulsar`

原文书写不规范，我们做下纠正

2021-11-24 01:12 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +Function Mesh 是一个 Kubernetes 的运算器 (operator)，用户在 Kubernetes 上运行 Pulsar 原生函数和 Pulsar 连接器，可充分运用 Kubernetes 的功能和资源。
`operator`专有名词，不翻译;
`Pulsar Functions`，不翻译;

2021-11-24 05:56 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +   [Function Mesh](/concepts/functionmesh-concepts.md) 是一个无服务器（Serverless）框架，用于协调多个 [Pulsar Functions](/concepts/pulsar-function-concepts.md) 和 [Pulsar IO 连接器](/concepts/pulsar-io-concepts.md)的流处理应用程
updated

2021-11-24 06:02 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +通过  Kafka on Pulsar (KoP) ， StreamNative Platform 中的 Pulsar brokers 支持原生的 Kafka 协议。因此，无需修改代码，就可以将现有的 Kafka 应用程序和服务迁移到 Apache Pulsar 上。
updated

2021-11-24 06:14 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +    | `username`| Kafka 客户端连接到 Pulsar 集群的用户名。设置为存储 Kafka 主题的 Pulsar 租户和命名空间（`TENANT_NAME/NAMESPACE_NAME`）的名称。 | `public/default` |
updated

2021-11-24 06:46 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +在完成[步骤 3 ](#step-3 use-pulsar-client-to-produce and-consume-events)和[步骤 4 ](#step-4 use-kafka-client-to-produce and-consume-events)后，Pulsar 生产者、Pulsar 消费者、Kafka 生产者和 Kafka 消费者都可正常运行。Pulsar 消费者可以从Puls
updated

2021-11-24 06:50 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +        * Pulsar 消费者
updated

2021-11-24 06:51 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +   * Pulsar 消费者
updated

2021-11-24 06:51 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +   * Kafka 消费者
updated

2021-11-24 06:51 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +StreamNative 控制台是基于 Web 的图形化界面（GUI）管理工具，用于管理和监控 Pulsar 。
updated

2021-11-24 06:53 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +   3. 为命名空间输入一个名称，然后点击**确定**。名称空间的名称最多包含 40 个字符，支持小写字母（a-z），数字字符（0-9），以及特殊字符连字符（-）。
updated

2021-11-24 06:54 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +    `sn-prometheus` 已暴露，其外部 IP 是 `{PROM-EXTERNAL-IP}`。
updated

2021-11-24 06:55 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +    `sn-grafana` 已暴露，其外部 IP 是`{GRAFANA-EXTERNAL-IP}`。
updated

2021-11-24 06:56 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +   现在你可以用 Grafana 仪表板查看组件的详细指标了，如 bookie、JVM、消息、节点、代理、Zookeeper、pulsar 主题等。
updated

2021-11-24 20:58 UTC, JipeiWang requested changes

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/concepts/functionmesh-concepts.md
> +通过 Function Mesh 提供的无服务器（Serverless）框架，用户可以组织 Pulsar Functions 和连接器。Function Mesh 简化了创建复杂流式作业的过程。对于寻求云原生无服务器（Serverless）流计算解决方案的用户来说，Function Mesh 是非常有价值的工具。
```suggestion
通过 Function Mesh 提供的无服务器（Serverless）框架，用户可以组建 Pulsar Functions 和连接器。Function Mesh 简化了创建复杂流式作业的过程。对于寻求云原生无服务器（Serverless）流计算解决方案的用户来说，Function Mesh 提供了强大的价值。
```

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/concepts/functionmesh-concepts.md
> +图 1 中给出一个**流**的例子。
concept 向下截至此处，对应的位置集体跳跃了

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/concepts/kop-concepts.md
> +为了让 Kafka 用户利用 Apache Pulsar 的多租户功能，Kafka 用户在使用 SASL （“Simple Authentication and Security Layer” 的缩写，即“简单认证和安全层”）认证机制对 Kafka 客户端进行认证时，可以指定 Pulsar 租户和命名空间作为其 SASL用户名。
```suggestion
为了让 Kafka 用户利用 Apache Pulsar 的多租户功能，Kafka 用户在使用 SASL （“Simple Authentication and Security Layer” 的缩写，即“简单认证和安全层”）认证机制对 Kafka 客户端进行认证时，可以指定 Pulsar 租户和命名空间作为其 SASL 用户名。
```

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/concepts/kop-concepts.md
> +KoP 对 Kafka 请求处理程序和 Pulsar 请求处理程序使用相同的主题查找方法。请求处理程序进行主题发现，在请求的主题分区查找所有权，并将所有权信息作为Kafka `TopicMetadata` 的一部分返回给 Kafka 客户端。
```suggestion
KoP 对 Kafka 请求处理程序和 Pulsar 请求处理程序使用相同的主题查找方法。请求处理程序进行主题发现，在请求的主题分区查找所有权，并将所有权信息作为 Kafka `TopicMetadata` 的一部分返回给 Kafka 客户端。
```

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/concepts/kop-concepts.md
> +要使 Pulsar 模型与 Kafka 模型保持一致难度很高。因此，为了与 Kafka 客户端完全兼容，KoP 通过在 Pulsar 的名为 `public/kafka/__offsets` 的系统主题中存储协调器组的变化和偏移量，部署了 Kafka 组协调器。这样就搭建了连接 Pulsar 和 Kafka 的桥梁，我们可以使用现有的 Pulsar 工具和策略，管理订阅和监控 Kafka 消费者
第一句话可以调整一下

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/quickstart.md
> +title: 开始
快速上手？Get started 还需要优化

2021-11-24 20:58 UTC, JipeiWang commented on v1.2.0/quickstart.md
> +- Kubernetes 服务器 v1.16 或更高版本
```suggestion
- 安装 Kubernetes 服务器 v1.16 或更高版本。
```

2021-11-25 02:22 UTC, infomagic-docs commented on v1.2.0/concepts/functionmesh-concepts.md
> +通过 Function Mesh 提供的无服务器（Serverless）框架，用户可以组织 Pulsar Functions 和连接器。Function Mesh 简化了创建复杂流式作业的过程。对于寻求云原生无服务器（Serverless）流计算解决方案的用户来说，Function Mesh 是非常有价值的工具。
updated: Function Mesh 提供了巨大的价值。

2021-11-25 02:22 UTC, infomagic-docs commented on v1.2.0/concepts/functionmesh-concepts.md
> +图 1 中给出一个**流**的例子。
fixed

2021-11-25 02:23 UTC, infomagic-docs commented on v1.2.0/concepts/kop-concepts.md
> +为了让 Kafka 用户利用 Apache Pulsar 的多租户功能，Kafka 用户在使用 SASL （“Simple Authentication and Security Layer” 的缩写，即“简单认证和安全层”）认证机制对 Kafka 客户端进行认证时，可以指定 Pulsar 租户和命名空间作为其 SASL用户名。
updated

2021-11-25 02:31 UTC, infomagic-docs commented on v1.2.0/concepts/kop-concepts.md
> +要使 Pulsar 模型与 Kafka 模型保持一致难度很高。因此，为了与 Kafka 客户端完全兼容，KoP 通过在 Pulsar 的名为 `public/kafka/__offsets` 的系统主题中存储协调器组的变化和偏移量，部署了 Kafka 组协调器。这样就搭建了连接 Pulsar 和 Kafka 的桥梁，我们可以使用现有的 Pulsar 工具和策略，管理订阅和监控 Kafka 消费者
updated

2021-11-25 02:31 UTC, infomagic-docs commented on v1.2.0/concepts/kop-concepts.md
> +要使 Pulsar 模型与 Kafka 模型保持一致难度很高。因此，为了与 Kafka 客户端完全兼容，KoP 通过在 Pulsar 的名为 `public/kafka/__offsets` 的系统主题中存储协调器组的变化和偏移量，部署了 Kafka 组协调器。这样就搭建了连接 Pulsar 和 Kafka 的桥梁，我们可以使用现有的 Pulsar 工具和策略，管理订阅和监控 Kafka 消费者
updated

2021-11-25 02:33 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +title: 开始
updated

2021-11-25 02:33 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +- Kubernetes 服务器 v1.16 或更高版本
updated

2021-11-25 02:38 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> -    pulsarctl tenants create TENANT_NAME
译文已删除

2021-11-25 11:01 UTC, infomagic-docs commented on v1.2.0/concepts/functionmesh-concepts.md
> +Function Mesh 是一个 Kubernetes 的运算器 (operator)，用户在 Kubernetes 上运行 Pulsar 原生函数和 Pulsar 连接器，可充分运用 Kubernetes 的功能和资源。
updated

2021-11-25 15:19 UTC, tuhaihe requested changes

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +    | `username`| Kafka 客户端连接到 Pulsar 集群的用户名。使用 Pulsar 租户和命名空间的名称（`TENANT_NAME/NAMESPACE_NAME`）进行设置，Kafka 主题存储在此 Pulsar 租户和命名空间中。 | `public/default` |
`It is set to the name of the Pulsar tenant and namespace (`TENANT_NAME/NAMESPACE_NAME`)`
-》该用户名会被设为 Pulsar 租户和命名空间的名称，Kafka 主题也将存储在此 。。。。中。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +- 无再平衡框架下的简化操作
可以将优点分开描述，更流畅易懂

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +- 利用 Pulsar 功能进行无服务器（Serverless）事件处理
`Pulsar Functions`专有名词

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +KoP 通过利用 Pulsar 已有的组件（如主题发现、分布式日志库——ManagedLedger、游标等），在 Pulsar 上实现 Kafka wire 协议。如需使用 KoP，可以下载 StreamNative Platform，并[开始使用](/quickstart.md)。
[开始使用]  - 翻译和文档名称一致吧

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +KoP 对 Kafka 请求处理程序和 Pulsar 请求处理程序使用相同的主题查找方法。请求处理程序进行主题发现，在请求的主题分区查找所有权，并将所有权信息作为 Kafka `TopicMetadata` 的一部分返回给 Kafka 客户端。
`请求处理程序 `-> `请求处理程序（request handler）`
加个英文原词注解吧，下同

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +Kafka 中，一旦消息被成功输出到某个主题分区，即会对这条消息分配一个偏移量。在 Pulsar 中，每条消息都被分配了一个`MessageID`。这个消息 ID 的构成包括： `ledger-id`、`entry-id`、和 `batch-index` 。KoP 在 Pulsar-Kafka 的包装中使用同样的方法，将 Pulsar 的 `MessageID ` 转换为偏移量，反之亦然。
produced ，还是按照 `生产` 翻译吧

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +当 Kafka 请求处理程序收到来自 Kafka 客户端产生的消息时，它通过逐一映射字段（如 key、value、timestamp 和 header）将 Kafka 消息转换为 Pulsar 消息，并使用 ManagedLedger append API 将这些转换后的 Pulsar 消息附加到 BookKeeper。将 Kafka 消息转换为 Pulsar 后，现有的 Pulsar 应用程序
append -> 追加
产生 -> 生产，后者更常用。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +当 Kafka 请求处理程序收到来自 Kafka 客户端的消费请求时，它会打开一个非持久性游标，从请求的偏移量开始读取条目。Kafka 请求处理程序将 Pulsar 消息转换回 Kafka 消息，以使现有的 Kafka 应用程序能够消费 Pulsar 客户端产生的消息。
entry -> 可不翻译，包括 ledger、bookie 都不翻译。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +最具挑战性的部分是部署组协调器和偏移量管理。Pulsar 没有集中的组协调器来为每个消费者组中的消费者分配分区或管理每个消费者组的偏移量。在 Pulsar 中，分区的分配是由 broker 在每个分区的基础上进行管理的，而偏移量的管理则是由该分区的所有者 broker 通过在游标中存储确认来完成的。
implement -> 实现；
组协调器，后面加上括号备注原英文吧，方便工程师理解，日常可能用英文比较多；

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/kop-concepts.md
> +要将 Pulsar 模型与 Kafka 模型进行对应匹配是很有难度的。因此，为了与 Kafka 客户端完全兼容，KoP 通过在 Pulsar 的名为 `public/kafka/__offsets` 的系统主题中存储协调器组的变化和偏移量，部署了 Kafka 组协调器。这样就搭建了连接 Pulsar 和 Kafka 的桥梁，我们可以使用现有的 Pulsar 工具和策略，管理订阅和监控 Kafka
重新优化翻译：`KoP implements the Kafka group coordinator by storing the coordinator group changes and offsets in a system topic called `public/kafka/__offsets` in Pulsar.`，implement 译为`实现`，就是 KoP 通过在 Pulsar 某些动作，来实现 Kafka 中的xxx功能。。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +通过 Function Mesh 提供的无服务器（Serverless）框架，用户可以组织 Pulsar Functions 和连接器。Function Mesh 简化了创建复杂流式作业的过程。对于寻求云原生无服务器（Serverless）流计算解决方案的用户来说，Function Mesh 提供了巨大的价值。
`组织`->`管理一组`

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +“流”是分区的、不可修改的、仅附加的事件序列，代表一系列过去的事实。例如，流事件可以模拟金融交易的序列，如先发生了“杰克借给爱丽丝一百美元”，然后发生了“爱丽丝借给鲍勃五十美元”。
`append-only`  -> `只追加（Append Only）`;
人名直接用英文吧，大家都能看得懂，译成中文怪怪的。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +**Function** 是轻量级的事件处理器，它从一个或多个输入流中得到消息，将用户提供的处理逻辑应用于一个或多个消息，并将处理逻辑的结果输出到另一个流。
重新优化 `A **function** is a lightweight event processor that consumes messages from one or more input streams,`

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +**Function** 是轻量级的事件处理器，它从一个或多个输入流中得到消息，将用户提供的处理逻辑应用于一个或多个消息，并将处理逻辑的结果输出到另一个流。
一条或多条消息。。。

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +图 2. 图中显示一个 function，它从一个或多个输入流中得到消息，并将结果输出到另一个流。
同上，需要优化

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +Function Mesh 与包含 Kubernetes 工具的通用语言和框架匹配，为解决常见部署问题节约时间。
重新优化

2021-11-25 15:19 UTC, tuhaihe commented on v1.2.0/concepts/functionmesh-concepts.md
> +设计 Function Mesh 是为了满足在 Kubernetes 上原生运行 Pulsar Function 和连接器。可以使用 `kubectl` 直接向 Kubernetes 集群提交 Function Mesh CRD，而无需使用 pulsar-admin CLI 工具向 Pulsar 集群发送 function 请求。安装在 Kubernetes 内部相应的 Mesh operato
`Pulsar Functions` 术语，专有名字

2021-11-28 09:26 UTC, infomagic-docs commented on v1.2.0/quickstart.md
> +    | `username`| Kafka 客户端连接到 Pulsar 集群的用户名。使用 Pulsar 租户和命名空间的名称（`TENANT_NAME/NAMESPACE_NAME`）进行设置，Kafka 主题存储在此 Pulsar 租户和命名空间中。 | `public/default` |
已按comment更新。我们之前的理解是这里需要用户输入已有的 Pulsar 租户和命名空间。所以实际是这个命令后，系统会为Kafka按这个名称创建新的pulsar租户和命名空间吗？

2021-11-28 11:17 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +通过 Function Mesh 提供的无服务器（Serverless）框架，用户可以组织 Pulsar Functions 和连接器。Function Mesh 简化了创建复杂流式作业的过程。对于寻求云原生无服务器（Serverless）流计算解决方案的用户来说，Function Mesh 提供了巨大的价值。
Updated.

2021-11-28 11:25 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +“流”是分区的、不可修改的、仅附加的事件序列，代表一系列过去的事实。例如，流事件可以模拟金融交易的序列，如先发生了“杰克借给爱丽丝一百美元”，然后发生了“爱丽丝借给鲍勃五十美元”。
Updated.

2021-11-28 11:25 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +**Function** 是轻量级的事件处理器，它从一个或多个输入流中得到消息，将用户提供的处理逻辑应用于一个或多个消息，并将处理逻辑的结果输出到另一个流。
Updated.

2021-11-28 11:25 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +图 2. 图中显示一个 function，它从一个或多个输入流中得到消息，并将结果输出到另一个流。
Updated.

2021-11-28 11:33 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +Function Mesh 与包含 Kubernetes 工具的通用语言和框架匹配，为解决常见部署问题节约时间。
Revised to:包含 Kubernetes 工具的通用语言和框架能够方便地与 Function Mesh 配套使用，为解决常见的部署问题节约了时间。

2021-11-28 11:36 UTC, Infomagic-ly commented on v1.2.0/concepts/functionmesh-concepts.md
> +设计 Function Mesh 是为了满足在 Kubernetes 上原生运行 Pulsar Function 和连接器。可以使用 `kubectl` 直接向 Kubernetes 集群提交 Function Mesh CRD，而无需使用 pulsar-admin CLI 工具向 Pulsar 集群发送 function 请求。安装在 Kubernetes 内部相应的 Mesh operato
Updated by deleting the "s".

2021-11-28 11:38 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +- 利用 Pulsar 功能进行无服务器（Serverless）事件处理
Updated.

2021-11-28 11:41 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +- 无再平衡框架下的简化操作
Updated to:
- 支持企业级多租户，操作精简流畅
- 无再平衡框架，简化操作

2021-11-28 11:42 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +KoP 通过利用 Pulsar 已有的组件（如主题发现、分布式日志库——ManagedLedger、游标等），在 Pulsar 上实现 Kafka wire 协议。如需使用 KoP，可以下载 StreamNative Platform，并[开始使用](/quickstart.md)。
Updated to "快速上手".

2021-11-28 11:46 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +KoP 对 Kafka 请求处理程序和 Pulsar 请求处理程序使用相同的主题查找方法。请求处理程序进行主题发现，在请求的主题分区查找所有权，并将所有权信息作为 Kafka `TopicMetadata` 的一部分返回给 Kafka 客户端。
Updated.

2021-11-28 11:48 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +Kafka 中，一旦消息被成功输出到某个主题分区，即会对这条消息分配一个偏移量。在 Pulsar 中，每条消息都被分配了一个`MessageID`。这个消息 ID 的构成包括： `ledger-id`、`entry-id`、和 `batch-index` 。KoP 在 Pulsar-Kafka 的包装中使用同样的方法，将 Pulsar 的 `MessageID ` 转换为偏移量，反之亦然。
Updated: 一旦在某个主题分区成功生产了消息，即会对这条消息分配一个偏移量。

2021-11-28 11:51 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +当 Kafka 请求处理程序收到来自 Kafka 客户端产生的消息时，它通过逐一映射字段（如 key、value、timestamp 和 header）将 Kafka 消息转换为 Pulsar 消息，并使用 ManagedLedger append API 将这些转换后的 Pulsar 消息附加到 BookKeeper。将 Kafka 消息转换为 Pulsar 后，现有的 Pulsar 应用程序
Updated.

2021-11-28 11:52 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +当 Kafka 请求处理程序收到来自 Kafka 客户端的消费请求时，它会打开一个非持久性游标，从请求的偏移量开始读取条目。Kafka 请求处理程序将 Pulsar 消息转换回 Kafka 消息，以使现有的 Kafka 应用程序能够消费 Pulsar 客户端产生的消息。
Updated.

2021-11-28 11:56 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +最具挑战性的部分是部署组协调器和偏移量管理。Pulsar 没有集中的组协调器来为每个消费者组中的消费者分配分区或管理每个消费者组的偏移量。在 Pulsar 中，分区的分配是由 broker 在每个分区的基础上进行管理的，而偏移量的管理则是由该分区的所有者 broker 通过在游标中存储确认来完成的。
Updated.

2021-11-28 12:01 UTC, Infomagic-ly commented on v1.2.0/concepts/kop-concepts.md
> +要将 Pulsar 模型与 Kafka 模型进行对应匹配是很有难度的。因此，为了与 Kafka 客户端完全兼容，KoP 通过在 Pulsar 的名为 `public/kafka/__offsets` 的系统主题中存储协调器组的变化和偏移量，部署了 Kafka 组协调器。这样就搭建了连接 Pulsar 和 Kafka 的桥梁，我们可以使用现有的 Pulsar 工具和策略，管理订阅和监控 Kafka
Updated.

2021-11-29 01:54 UTC, tuhaihe commented on v1.2.0/quickstart.md
> +    | `username`| Kafka 客户端连接到 Pulsar 集群的用户名。使用 Pulsar 租户和命名空间的名称（`TENANT_NAME/NAMESPACE_NAME`）进行设置，Kafka 主题存储在此 Pulsar 租户和命名空间中。 | `public/default` |
嗯，该字段用于 Kafka 的设置，也会用于 Pulsar 。

2021-11-29 04:11 UTC, infomagic-docs commented on v1.2.0/concepts/functionmesh-concepts.md
> +“流”是分区的、不可修改的、仅附加的事件序列，代表一系列过去的事实。例如，流事件可以模拟金融交易的序列，如先发生了“杰克借给爱丽丝一百美元”，然后发生了“爱丽丝借给鲍勃五十美元”。
漏掉的已更新：`append-only` -> `只追加（Append Only）`

2021-11-29 04:35 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2021-11-29 04:36 UTC, merged