Update work-with-tenants.md
streamnative/snp-cn pull request #40
Opened 2021-12-19 11:50 UTC by infomagic-docs

2021-12-19 11:54 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
cloud 环境的 UI 中看到的是 Add Role，对应中文 UI 是添加角色 。而此处原文是 New Role，所以没按cloud UI来，请确认使用哪个译文？

2021-12-19 11:54 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   ![](../../image/delete-tenant.png)
修复。

2021-12-20 09:46 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -4. Click **Confirm**.
漏了一行

2021-12-20 09:46 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
我的建议是按照 UI。

2021-12-20 13:30 UTC, Huanli-Meng commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
我记得之前好像是之前没有添加任何角色，应该是 new role，一旦有了角色，再去添加，这个按钮就变成 add role了。

2021-12-20 23:10 UTC, tuhaihe requested changes

2021-12-20 23:10 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
貌似2个意思对应中文一样，新建 或 添加 差别不大，可按 UI 翻译。

2021-12-21 02:08 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -4. Click **Confirm**.
Updated. Thanks.

2021-12-21 02:12 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
谢谢，已按 UI 翻译：添加角色

2021-12-21 02:13 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-tenants.md
> -   * To add administrators, click **New Role** and then select one or more users or service accounts from the drop-down list.
> 我记得之前好像是之前没有添加任何角色，应该是 new role，一旦有了角色，再去添加，这个按钮就变成 add role了。你可以试一下，然后看看是不是这样。如果真的存在文档和 UI 不一致的情况，就按UI 走。

试了以下，好像不管之前有没有角色，都是 Add Role

2021-12-21 02:54 UTC, tuhaihe approved these changes

2021-12-21 02:55 UTC, merged