Update work-with-namespaces.md
streamnative/snp-cn pull request #41
Opened 2021-12-21 08:14 UTC by infomagic-docs

2021-12-21 08:19 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> -    <td rowspan="3" >Dispatch Rate
这部分和UI差距较大。Dispatch Rate 目前统一用的术语表的”调度速率“。是否改成 消费速率？感觉意思变化有点大，没有改。  
另外，UI上没有 Dispatch Rate Per Consumer，只有 Subscribe Rate Per Consumer，而且单位是 subscribes/second。不知道是不是同一个东西。

2021-12-21 16:47 UTC, JipeiWang requested changes

2021-12-21 16:47 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +   **Mark-Delete Rate**：每秒允许的 mark-deletion 的调用次数。当该值设置为 0 时，则禁用速率限制器。默认值为 0。</p>
Rate 是否需要翻译？

2021-12-21 16:47 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>Schema 有效性：为没有 schema 的生产者启用/禁用架构验证。如果禁用，则不允许没有 schema 的生产者向具有 schema 的主题生产消息。
```suggestion
    <li>Schema 有效性：为没有 schema 的生产者启用/禁用验证。如果禁用，则不允许没有 schema 的生产者向具有 schema 的主题生产消息。
```
`有效性`对应的原文翻译是不是应该`验证强制执行`

2021-12-21 16:47 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> -    <td rowspan="3" >Dispatch Rate
可以按调度翻译，目前我们在社区也用调度来翻译 dispatch。
如果 UI 上没有该项，可能是 UI 更新了。我再和作者确认一下，应该是以 UI 为准。

2021-12-21 16:47 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>最大生产者数量（基于主题）：每个主题支持的最大生产者的数量。
从这项开始列表里的 configure 都没有翻译。上文翻译为“配置”，下文的翻译需同步。

2021-12-22 05:20 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> -    <td rowspan="3" >Dispatch Rate
目前翻译统一用的调度。不过 UI 上没有用调度，比如Dispatch Rate Per Consumer在UI上翻译消费速率。  
也许是翻译需要更新。  
我看到UI是 Cloud SN，是不是 Platform 和 cloud 版本本来就有区别。

总之，现在的翻译如需修改，麻烦直接指出哪个label翻译成什么，谢谢。

2021-12-22 05:21 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +   **Mark-Delete Rate**：每秒允许的 mark-deletion 的调用次数。当该值设置为 0 时，则禁用速率限制器。默认值为 0。</p>
副本因子下的这4个参数，在UI上都没有翻译。

2021-12-22 05:30 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>Schema 有效性：为没有 schema 的生产者启用/禁用架构验证。如果禁用，则不允许没有 schema 的生产者向具有 schema 的主题生产消息。
UI 上的英文原文确实是“Schema Validation Enforced”，但是 UI 上的中文版是“Schema 有效性“，是否是UI 本身的翻译需要更新？

2021-12-22 05:33 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>最大生产者数量（基于主题）：每个主题支持的最大生产者的数量。
Updated

2021-12-22 08:35 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +   **Mark-Delete Rate**：每秒允许的 mark-deletion 的调用次数。当该值设置为 0 时，则禁用速率限制器。默认值为 0。</p>
好的

2021-12-22 08:38 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>Schema 有效性：为没有 schema 的生产者启用/禁用架构验证。如果禁用，则不允许没有 schema 的生产者向具有 schema 的主题生产消息。
好的，那就按 UI 的中文为标准。

2021-12-26 15:55 UTC, tuhaihe requested changes

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +如下示例显示了如何从当前的服务中的 broker 卸载 `example-tenant/example-ns`。
当前的服务中的 -> 当前服务中的，否则有点啰嗦

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <td>授予/撤消其他客户端角色在此命名空间中的权限。
撤销权限，撤消动作？我们可不做严格区分，保持翻译一致即可。

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +   **需要加密**：为命名空间启用/禁用消息加密。<ul><li> 使能：为命名空间启用消息加密。<li> 禁用：为命名空间禁用消息加密。</ul>
使能 -> 启用，下同。

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    **堆积量**：命名空间允许的最大堆积量（以字节为单位）。堆积量必须小于 1000000000 字节。默认设置为 -1073741824 字节。</p> **Backlog 保留策略**：backlog 的保留策略。<ul><li> consumer_backlog_eviction：broker 开始移除 backlog 消息。<li>producer_exception：broker
Backlog Quota Size：这里的 Backlog 还是保持不译，与全文保持一致。下同，请更新

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>消息 TTL（秒）：配置消息 TTL（秒）。在 TTL 周期内，如果没有任何消费者消费该消息，当 TTL 周期结束后，该消息被标记为“已消费”。
没有任何消费者：英文单词有漏译文，请补充

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>卸载阈值（字节）：配置阈值以卸载消息。当达到阈值时，消息会自动卸载到层级存储。默认值为 -1。
配置阈值以卸载消息：保持同上格式翻译。

2021-12-26 15:55 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> -    <td rowspan="3" >Dispatch Rate
可按@Jipei 建议，按调度翻译。

2021-12-28 01:24 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <td>授予/撤消其他客户端角色在此命名空间中的权限。
已统一成撤销，thanks

2021-12-28 01:24 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +   **需要加密**：为命名空间启用/禁用消息加密。<ul><li> 使能：为命名空间启用消息加密。<li> 禁用：为命名空间禁用消息加密。</ul>
Updated

2021-12-28 01:31 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    **堆积量**：命名空间允许的最大堆积量（以字节为单位）。堆积量必须小于 1000000000 字节。默认设置为 -1073741824 字节。</p> **Backlog 保留策略**：backlog 的保留策略。<ul><li> consumer_backlog_eviction：broker 开始移除 backlog 消息。<li>producer_exception：broker
改成了 Backlog 堆积量

2021-12-28 01:37 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>消息 TTL（秒）：配置消息 TTL（秒）。在 TTL 周期内，如果没有任何消费者消费该消息，当 TTL 周期结束后，该消息被标记为“已消费”。
updated

2021-12-28 01:39 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +    <li>卸载阈值（字节）：配置阈值以卸载消息。当达到阈值时，消息会自动卸载到层级存储。默认值为 -1。
Updated

2021-12-28 01:40 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> -    <td rowspan="3" >Dispatch Rate
目前是按调度翻译的

2021-12-28 01:40 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-namespaces.md
> +如下示例显示了如何从当前的服务中的 broker 卸载 `example-tenant/example-ns`。
Updated

2021-12-28 13:09 UTC, tuhaihe approved these changes

2021-12-28 13:09 UTC, merged