Update work-with-topics.md
streamnative/snp-cn pull request #42
Opened 2021-12-22 07:21 UTC by infomagic-docs

2021-12-22 07:23 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>SKIP: skip some messages for the subscription.
UI 上没找到此选项，请确认翻译。

2021-12-22 07:23 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>RESET BY ID: reset the ID of the message at which the subscription is created.
UI 上没找到此选项，请确认翻译。

2021-12-22 07:23 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>RESET BY TIME: reset the time when the subscription is created.
UI 上没找到此选项，请确认翻译。

2021-12-22 07:23 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>PEEK: peek some messages for the subscription.
UI 上没找到此选项，请确认翻译。

2021-12-27 18:17 UTC, JipeiWang requested changes

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +本文介绍如何了使用 pulsarctl CLI （命令行工具）或 StreamNative 控制台为集群创建和管理主题。
需要检查空格

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +## 消息 schema
manage 不是 message 哈

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +启用 schema 后，Pulsar 在解析数据时将字节作为输入并发送字节作为输出。
```suggestion
启用 schema 后，Pulsar 在解析数据时接受字节作为输入并发送字节作为输出。
```

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <td>存储大小
存储量？

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <td>表示存储的大小。
```suggestion
    <td>存储的大小。
```
这样感觉能把 item 和 description 区分开。

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>Ledger 大小：写入 ledge 消息的大小（单位为字节）。
ledger 少了个 r，后面也有遗漏。

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>挂起读取操作：正在进行的对 BookKeeper 的读取请求的数量。
```suggestion
    <li>挂起读取操作：对正在进行的 BookKeeper 读取请求的数量。
```

2021-12-27 18:17 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>functions：授予/撤销 Pulsar Function 操作。
action 是翻译为 行为 还是 操作 比较合适？action 是不是需要和 operation 区分开？

2021-12-28 01:43 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +本文介绍如何了使用 pulsarctl CLI （命令行工具）或 StreamNative 控制台为集群创建和管理主题。
Fixed

2021-12-28 01:45 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +## 消息 schema
Fixed.

2021-12-28 01:46 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +启用 schema 后，Pulsar 在解析数据时将字节作为输入并发送字节作为输出。
Updated.

2021-12-28 01:47 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <td>存储大小
界面上是“存储大小”

2021-12-28 01:48 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <td>表示存储的大小。
Updated

2021-12-28 01:49 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>Ledger 大小：写入 ledge 消息的大小（单位为字节）。
Fixed.

2021-12-28 01:51 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>挂起读取操作：正在进行的对 BookKeeper 的读取请求的数量。
Updated

2021-12-28 02:05 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-topics.md
> +    <li>functions：授予/撤销 Pulsar Function 操作。
直译的话应该是“动作”，按意思的话好像用“权限”更通顺。请确认。namespace 页面也有同样的内容，确认后我们统一改一下

2021-12-28 02:26 UTC, Huanli-Meng commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>SKIP: skip some messages for the subscription.
先创建一个 subscription，然后再backlog 那一列的三个点，点击一下，然后就会跳出选项。
![image](https://user-images.githubusercontent.com/48120384/147520927-61d72a52-430d-4ae5-a08e-1749dcd2612c.png)

2021-12-28 02:29 UTC, Huanli-Meng commented on v1.2.0/user-guides/admin/work-with-topics.md
> -    <li>RESET BY TIME: reset the time when the subscription is created.
创建 subscription 之后，在 Partition 区域，随便点击一个，进入到下面的页面，就可以看见了。
![image](https://user-images.githubusercontent.com/48120384/147521153-390fbfb9-37f6-42d3-88d4-f17ae0b09b24.png)

2021-12-28 02:29 UTC, Huanli-Meng reviewed
Add comments about how to find related buttons.

2022-01-03 12:38 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2022-01-03 12:38 UTC, merged