Update connector-pulsarctl.md
streamnative/snp-cn pull request #43
Opened 2021-12-24 03:43 UTC by infomagic-docs

2021-12-24 03:45 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> -When you want to modify sink or sink configurations, or update resources for a sink or source connector, you can update connectors.
原文 modify sink or sink configurations， 感觉应该是 sink or source，类似后半句。译文按 sink or source 处理了，请确认。

2021-12-26 14:54 UTC, tuhaihe requested changes

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +title: 通过 pulsarctl CLI 使用连接器
可以把 CLI 直接删掉

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +本文介绍了如何使用 pulsarctl  CLI（命令行工具）来创建、更新和删除连接器。有关 pulsarctl  CLI（命令行工具）支持操作的完整列表，参见[此处](https://docs.streamnative.io/pulsarctl/v2.7.0.7/)。
检查下多余空格

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +2. 通过指定特定字段，创建连接器。如需了解所有支持的字段，参见 [Source 和 sink 配置支持选项](#source-和-sink-配置支持选项)。
Source 和 sink：首字母大小写保持一致

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> -When you want to modify sink or sink configurations, or update resources for a sink or source connector, you can update connectors.
确认 👍 原文应该有误

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `-a`, `--archive` | Source 的 NAR 存档的路径。 <br/>同样支持 url-path（http/https/file [文件协议，假定文件已经存在于worker 主机上]），worker 可以从该路径下载包。 |
`存在于worker 主..`：注意空格

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `--cpu` | 需要为每个 source 实例分配的 CPU（以核为单位）（仅适用于 Docker 运行时）。 |
`以核为单位` -> `核数` ，比较符合日常表达习惯

2021-12-26 14:54 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `-st`, `--schema-type` | Schema 的类型。<br>用于从 source 发出的消息的编码，可以是内置 schema（例如，AVRO 和 JSON）或是自定义 schema 类的名称。 |
用于从 source 发出的消息的编码 -> 用于编码... 优化下译法

2021-12-27 07:24 UTC, JipeiWang requested changes

2021-12-27 07:24 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +> 在使用连接器之前，需确保命名空间已被授予 `function`  权限。
此处多余空格，后文也有，麻烦再过一遍。

2021-12-29 08:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +title: 通过 pulsarctl CLI 使用连接器
Updated

2021-12-29 08:23 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +本文介绍了如何使用 pulsarctl  CLI（命令行工具）来创建、更新和删除连接器。有关 pulsarctl  CLI（命令行工具）支持操作的完整列表，参见[此处](https://docs.streamnative.io/pulsarctl/v2.7.0.7/)。
Fixed.

2021-12-29 08:24 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +2. 通过指定特定字段，创建连接器。如需了解所有支持的字段，参见 [Source 和 sink 配置支持选项](#source-和-sink-配置支持选项)。
Updated

2021-12-29 08:26 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `-a`, `--archive` | Source 的 NAR 存档的路径。 <br/>同样支持 url-path（http/https/file [文件协议，假定文件已经存在于worker 主机上]），worker 可以从该路径下载包。 |
Fixed

2021-12-29 08:27 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `--cpu` | 需要为每个 source 实例分配的 CPU（以核为单位）（仅适用于 Docker 运行时）。 |
Updated

2021-12-29 08:42 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `-st`, `--schema-type` | Schema 的类型。<br>用于从 source 发出的消息的编码，可以是内置 schema（例如，AVRO 和 JSON）或是自定义 schema 类的名称。 |
Updated.

2021-12-29 08:44 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +> 在使用连接器之前，需确保命名空间已被授予 `function`  权限。
多余空格都过了一遍。

2021-12-30 12:45 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `--cpu` | 需要为每个 source 实例分配的 CPU（以核为单位）（仅适用于 Docker 运行时）。 |
Line 172，请更新下 @infomagic-docs

2022-01-03 12:29 UTC, tuhaihe commented
@infomagic-docs Line 172，请更新。

2022-01-06 06:50 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-pulsarctl.md
> +| `--cpu` | 需要为每个 source 实例分配的 CPU（以核为单位）（仅适用于 Docker 运行时）。 |
已更新

2022-01-17 08:03 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2022-01-17 08:03 UTC, merged