Update connector-crd.md
streamnative/snp-cn pull request #44
Opened 2021-12-27 07:31 UTC by infomagic-docs

2021-12-27 17:53 UTC, JipeiWang requested changes

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkSerdeClassName` | 输出主题到 SerDe 类名称的映射（ JSON 字符串）。          |
之前的 ”as a JSON string“ 都翻译为 “为 JSON 字符串”，最好保持一致。

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能使用高于 `request ` 的更多资源，这是允许的。但是 Pod 使用的资源不得超过该资源的 `limit`。
```suggestion
则 Pod 可能、也被允许使用高于 `request ` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
```

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
这句需要重新翻译～

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `TerminationGracePeriodSeconds` | Kubernetes 终止 Pod 前的时间。                        |
```suggestion
| `TerminationGracePeriodSeconds` | Kubernetes 终止 Pod 前的时长。                        |
```
感觉换成时长更准确。

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkConfig                    | 指定 sink 连接器配置的 ConfigMap 映射。                      |
```suggestion
| `SinkConfig`                    | 指定 sink 连接器配置的 ConfigMap 映射。                      |
```

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `DeadLetterTopic` | 所有发送消息均未成功处理的主题。                             |
这里逻辑感觉反了

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `Topics` | 消息来源的主题。                                |
configuration 未翻译

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +在指定 function 或连接器时，可以选择指定它们需要多少资源。可指定的资源包括 CPU 和内存（RAM）。
前文 function 单独时曾翻译为 函数，上下文请保持一致。

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能使用高于 `request` 的更多资源，这是允许的。但是 Pod 使用的资源不得超过该资源的 `limit`。
同上

2021-12-27 17:53 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSerdeSources` | 输入主题到 SerDe 类名称的映射（ JSON 字符串）。 |
JSON 字符串这里同上

2021-12-28 02:07 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkSerdeClassName` | 输出主题到 SerDe 类名称的映射（ JSON 字符串）。          |
Updated. Thanks.

2021-12-28 02:08 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能使用高于 `request ` 的更多资源，这是允许的。但是 Pod 使用的资源不得超过该资源的 `limit`。
Updated

2021-12-28 02:17 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
Updated.

2021-12-28 02:17 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
Updated.

2021-12-28 02:17 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `TerminationGracePeriodSeconds` | Kubernetes 终止 Pod 前的时间。                        |
Updated

2021-12-28 02:18 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkConfig                    | 指定 sink 连接器配置的 ConfigMap 映射。                      |
Fixed

2021-12-28 02:21 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `DeadLetterTopic` | 所有发送消息均未成功处理的主题。                             |
Updated

2021-12-28 02:26 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `Topics` | 消息来源的主题。                                |
已修改成“消息来源主题的配置。”

不过根据output那边的topic的描述“The output topic of a Pulsar Function”。这个参数就是指定一个主题吧，也没有什么更多的配置。所以感觉原来的翻译更简洁一些。

2021-12-28 02:29 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +在指定 function 或连接器时，可以选择指定它们需要多少资源。可指定的资源包括 CPU 和内存（RAM）。
均已更新

2021-12-28 02:30 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能使用高于 `request` 的更多资源，这是允许的。但是 Pod 使用的资源不得超过该资源的 `limit`。
Updated

2021-12-28 02:30 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSerdeSources` | 输入主题到 SerDe 类名称的映射（ JSON 字符串）。 |
Updated

2021-12-28 06:21 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
在要使用密钥值的每个容器中修改 Pod 定义，为要使用的每个密钥添加环境变量。

2022-01-03 14:29 UTC, tuhaihe requested changes

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +### 基础运行器
运行器 -> 运行器（Runder）

加个备注吧，目前译法不太常见，添加英文备注方便理解，同下。

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkSerdeClassName` | 输出主题到 SerDe 类名称的映射（为  JSON 字符串）。        |
注意空格

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSchemaSinks` | 输出主题到 Schema 类名称的映射（为  JSON 字符串）。 |
注意空格

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request ` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
结合上下文，此处 `request`、`limit` 不是命令，只是强调。意思时 被允许使用高于自身所需资源的更多资源、自身资源限制此类意思。

请更新翻译。

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 对于需要使用密钥的值的容器，需要为其修改的 Pod 定义，为每个要使用的密钥添加环境变量。
`需要为其修改的 Pod 定义` -> `需要为其修改 Pod 的定义`

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `MaxReplicas`| Sink 连接器运行的 Pulsar 实例的最大值。当 `maxReplicas` 参数的值大于 `replicas` 的值时，表明 sink 控制器根据 CPU 的使用情况自动扩展源连接器。默认情况下，`maxReplicas` 设置为 0，表明自动调节功能被禁用。 |
源连接器 -> 请更新；
自动调节 -> 自动扩展 - 同上某处同一翻译用词一起更新。

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `LogTopic` | 生成的 source 连接器日志的主题。                             |
此处翻译请更新，有点别扭

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSerdeSources` | 输入主题到 SerDe 类名称的映射（为  JSON 字符串）。 |
注意空格，同下。

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SourceSpecs` | Source 具体配置到消费者具体配置的映射。消费者具体配置包括以下选项：<br />- `SchemaType`：连接器获取的消息可使用的内置 schema 类型或自定义 schema 类的名称。<br />- `SerdeClassName`：连接器获取的消息所使用的 SerDe 类。<br />- `IsRegexPattern`：配置输入主题是否采用
是否采用 Regex 模式 -> 是否采用正则表达式模式

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
同之前建议

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
翻译不完整，漏掉了部分。

2022-01-03 14:29 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +    | tlsHostnameVerificationEnable | 启用  hostname 验证。    |
注意空格。。

2022-01-06 06:55 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +### 基础运行器
在主要标题加了备注（Runner）

2022-01-06 06:57 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SinkSerdeClassName` | 输出主题到 SerDe 类名称的映射（为  JSON 字符串）。        |
fixed. 已全文检查双空格。

2022-01-06 06:58 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSchemaSinks` | 输出主题到 Schema 类名称的映射（为  JSON 字符串）。 |
fixed. 已全文检查双空格。

2022-01-06 07:06 UTC, danwen1 commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request ` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
我们觉得这个应该是对应的 yaml 里 resource 的 request 和 limit 设置，比如下面的例子。保留英文是不是更好对应。我们建议保留英文。

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```

2022-01-06 07:06 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 对于需要使用密钥的值的容器，需要为其修改的 Pod 定义，为每个要使用的密钥添加环境变量。
Updated.

2022-01-06 07:07 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `MaxReplicas`| Sink 连接器运行的 Pulsar 实例的最大值。当 `maxReplicas` 参数的值大于 `replicas` 的值时，表明 sink 控制器根据 CPU 的使用情况自动扩展源连接器。默认情况下，`maxReplicas` 设置为 0，表明自动调节功能被禁用。 |
updated.

2022-01-06 07:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `LogTopic` | 生成的 source 连接器日志的主题。                             |
updated.

2022-01-06 07:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `CustomSerdeSources` | 输入主题到 SerDe 类名称的映射（为  JSON 字符串）。 |
已全文检查

2022-01-06 07:24 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +| `SourceSpecs` | Source 具体配置到消费者具体配置的映射。消费者具体配置包括以下选项：<br />- `SchemaType`：连接器获取的消息可使用的内置 schema 类型或自定义 schema 类的名称。<br />- `SerdeClassName`：连接器获取的消息所使用的 SerDe 类。<br />- `IsRegexPattern`：配置输入主题是否采用
updated

2022-01-06 07:25 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
参考上文回复。

2022-01-06 07:28 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +2. 修改每个容器中的 Pod 定义，如果要使用密钥的值，则需要为每个密钥添加环境变量。
Updated

2022-01-06 07:28 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +    | tlsHostnameVerificationEnable | 启用  hostname 验证。    |
已全文检查

2022-01-17 08:11 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request ` 的更多资源。但是 Pod 使用的资源不得超过该资源的 `limit`。
同意👍

2022-01-17 08:21 UTC, tuhaihe approved these changes
@tuhaihe Approve this PR.

2022-01-17 08:21 UTC, merged