Update function-pulsarctl.md
streamnative/snp-cn pull request #46
Opened 2021-12-31 05:20 UTC by infomagic-docs

2021-12-31 05:21 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> -This table lists all fields available for creating a Pulsar function.
原文这句话连续出现了两次，应该是原文错误。译文只翻译一次。

2021-12-31 05:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> -When you want to update the configuration options of a Pulsar Function, you can use the `pulsarctl functions update` command to delete it.
原文是“to delete it”，应该是原文错误，本节是update，下一节才是delete。译文按 update 处理了。

2022-01-03 15:07 UTC, tuhaihe requested changes

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +title: 通过 pulsarctl 使用 Pulsar Function
Pulsar Function -> Pulsar Functions

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +title: 通过 pulsarctl 使用 Pulsar Function
代指总功能，用 Pulsar Functions，代指一条 Function - 则用单数。下面同步更新。

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +为 Pulsar 集群创建 Pulsar Function 后，可以根据需要更新或删除这个 function。本文介绍了如何使用 pulsarctl CLI （命令行工具）来更新和删除 Pulsar Function。有关 pulsarctl CLI（命令行工具）支持操作的完整列表，参见 [pulsarctl 命令参考](https://docs.streamnative.io/pulsarct
为 Pulsar 集群创建 Pulsar Function 后 -> 为 Pulsar 集群创建一条 Pulsar Function 后

可以添加 `一条` 明确创建的是一个函数，下面指一个函数时请添加 `一条`

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +# 创建 Pulsar Function
复数

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> -This table lists all fields available for creating a Pulsar function.
确认 👍

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +subs-name | 用于用户想要为输入主题消费者指定特定的订阅名称时，表示 Pulsar 源订阅名称。 |
源 -> source

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +topics-pattern | 定义主题列表的主题模式。命名空间下与主题模式匹配的主题将被消费。`--input` 和 `--topics-Pattern` 是互斥的。<br/>可在 `--customSerdeInputs` 中为模式添加 SerDe 类名（仅支持 Java 函数）。 |
重新翻译，保持 --custom-serde-inputs 类名不变。。

2022-01-03 15:07 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> -When you want to update the configuration options of a Pulsar Function, you can use the `pulsarctl functions update` command to delete it.
确认。

2022-01-04 18:34 UTC, JipeiWang requested changes

2022-01-04 18:34 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +为 Pulsar 集群创建 Pulsar Function 后，可以根据需要更新或删除这个 function。本文介绍了如何使用 pulsarctl CLI （命令行工具）来更新和删除 Pulsar Function。有关 pulsarctl CLI（命令行工具）支持操作的完整列表，参见 [pulsarctl 命令参考](https://docs.streamnative.io/pulsarct
```suggestion
为 Pulsar 集群创建 Pulsar Function 后，可以根据需要更新或删除这个 **function**。本文介绍了如何使用 pulsarctl CLI （命令行工具）来更新和删除 Pulsar Function。有关 pulsarctl CLI（命令行工具）支持操作的完整列表，参见 [pulsarctl 命令参考](https://docs.streamnative.io/pulsarctl/v2.7.0.7/)。
```
加粗的这里不建议这样翻译。小写作 function 的时候在其他 PR 是翻译为“函数”的，这里是特指 Pulsar Function。可以翻译为 “更新或删除这个 Pulsar Function”，或者“可以根据需要将其更新或删除”

2022-01-04 18:34 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +auto-ack | 框架是否自动确认消息。                                       | true
```suggestion
auto-ack | 框架是否自动确认消息。                                       | true |
```

2022-01-04 18:34 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +auto-ack | 框架是否自动确认消息。                                       | true
下面的列表都缺失了最后一列，应该都在句尾加上 |

2022-01-04 18:34 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +dead-letter-topic | 所有未成功处理的消息被发送到的主题。Python 函数不支持这一参数。 |
Python Functions 同 Pulsar Functions 一样不做翻译

2022-01-04 18:34 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +schema-type | 内置 schema 类型或自定义 schema 类名称，用于 function 输出消息。 | <empty string>
这里function应该是函数

2022-01-06 07:58 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +title: 通过 pulsarctl 使用 Pulsar Function
Updated

2022-01-06 08:05 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +为 Pulsar 集群创建 Pulsar Function 后，可以根据需要更新或删除这个 function。本文介绍了如何使用 pulsarctl CLI （命令行工具）来更新和删除 Pulsar Function。有关 pulsarctl CLI（命令行工具）支持操作的完整列表，参见 [pulsarctl 命令参考](https://docs.streamnative.io/pulsarct
updated

2022-01-06 08:05 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +# 创建 Pulsar Function
updated

2022-01-06 08:06 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +subs-name | 用于用户想要为输入主题消费者指定特定的订阅名称时，表示 Pulsar 源订阅名称。 |
updated

2022-01-06 08:11 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +topics-pattern | 定义主题列表的主题模式。命名空间下与主题模式匹配的主题将被消费。`--input` 和 `--topics-Pattern` 是互斥的。<br/>可在 `--customSerdeInputs` 中为模式添加 SerDe 类名（仅支持 Java 函数）。 |
updated

2022-01-06 08:13 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +schema-type | 内置 schema 类型或自定义 schema 类名称，用于 function 输出消息。 | <empty string>
updated

2022-01-06 08:24 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +auto-ack | 框架是否自动确认消息。                                       | true
updated

2022-01-06 08:26 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +为 Pulsar 集群创建 Pulsar Function 后，可以根据需要更新或删除这个 function。本文介绍了如何使用 pulsarctl CLI （命令行工具）来更新和删除 Pulsar Function。有关 pulsarctl CLI（命令行工具）支持操作的完整列表，参见 [pulsarctl 命令参考](https://docs.streamnative.io/pulsarct
Updated

2022-01-06 08:28 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-pulsarctl.md
> +dead-letter-topic | 所有未成功处理的消息被发送到的主题。Python 函数不支持这一参数。 |
updated

2022-01-17 13:51 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2022-01-17 13:51 UTC, merged