Update function-crd.md
streamnative/snp-cn pull request #47
Opened 2021-12-31 09:26 UTC by infomagic-docs

2022-01-03 15:32 UTC, tuhaihe requested changes

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +title: Pulsar Function CRD 配置
Functions：复数不变

处理情况，同 https://github.com/streamnative/snp-cn/pull/46 介绍说明，请全文更新。

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +Pulsar Function 是一种简洁的计算抽象，Apache Pulsar 通过它可以让用户能够表达简单的 ETL 和流任务。目前 Function Mesh 支持使用 Java、Python 或 Go 编程语言来定义 Function 的 YAML 文件。
能够表达 -》 能够处理

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `SourceSpecs` | Source 具体配置到消费者具体配置的映射。消费者具体配置包括以下选项：<br />- `SchemaType`：function 获取的消息使用的内置 schema 类型或自定义 schema 类的名称。<br />- `SerdeClassName`：function 获取的消息的 SerDe 类。<br />- `IsRegexPattern`：配置输
需要注意点，同之前文档说明。

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `SourceSpecs` | Source 具体配置到消费者具体配置的映射。消费者具体配置包括以下选项：<br />- `SchemaType`：function 获取的消息使用的内置 schema 类型或自定义 schema 类的名称。<br />- `SerdeClassName`：function 获取的消息的 SerDe 类。<br />- `IsRegexPattern`：配置输
function 获取消息的架构属性：重译

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request` 的更多资源。但 Pod 使用的资源不得超过该资源的 `limit`。
同之前文档。

2022-01-03 15:32 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +1. 对于需要使用密钥的值的容器，需要为其修改的 Pod 定义，为每个要使用的密钥添加环境变量。
更新。

2022-01-04 18:14 UTC, JipeiWang requested changes

2022-01-04 18:14 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `LogTopic` | 产生 Pulsar Function 日志的主题。                            |
```suggestion
| `LogTopic` | 产生 Pulsar Function 日志的主题。                            |
```
produce 在 Pulsar 一直做“生产”翻译哈

2022-01-04 18:14 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +1. 修改镜像和/或命令行，以便程序查找指定的环境变量的值。
以上序号不对

2022-01-06 07:37 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +title: Pulsar Function CRD 配置
Updated.

2022-01-06 07:38 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +Pulsar Function 是一种简洁的计算抽象，Apache Pulsar 通过它可以让用户能够表达简单的 ETL 和流任务。目前 Function Mesh 支持使用 Java、Python 或 Go 编程语言来定义 Function 的 YAML 文件。
Updated.

2022-01-06 07:42 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `SourceSpecs` | Source 具体配置到消费者具体配置的映射。消费者具体配置包括以下选项：<br />- `SchemaType`：function 获取的消息使用的内置 schema 类型或自定义 schema 类的名称。<br />- `SerdeClassName`：function 获取的消息的 SerDe 类。<br />- `IsRegexPattern`：配置输
updated

2022-01-06 07:42 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +如果运行 Pod 的节点有足够的可用资源，则 Pod 可能、也被允许使用高于 `request` 的更多资源。但 Pod 使用的资源不得超过该资源的 `limit`。
已在前文档回复

2022-01-06 07:46 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +1. 对于需要使用密钥的值的容器，需要为其修改的 Pod 定义，为每个要使用的密钥添加环境变量。
此处已经是修改过的翻译，和之前那个文件的已经修改过，目前这里觉得意思是对的。能否明确一下哪个地方有问题？

2022-01-06 07:46 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +1. 对于需要使用密钥的值的容器，需要为其修改的 Pod 定义，为每个要使用的密钥添加环境变量。
此处已经是修改过的翻译，和之前那个文件的已经修改过，目前这里觉得意思是对的。能否明确一下哪个地方有问题？

2022-01-06 07:49 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `LogTopic` | 产生 Pulsar Function 日志的主题。                            |
updated

2022-01-06 07:52 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +1. 修改镜像和/或命令行，以便程序查找指定的环境变量的值。
fixed.

2022-01-17 14:05 UTC, tuhaihe requested changes

2022-01-17 14:05 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `FuncConfig` | 到 ConfigMap 的映射，指定 Pulsar 函数的配置。            |
Pulsar Function 不翻译

2022-01-17 14:06 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `FuncConfig` | 到 ConfigMap 的映射，指定 Pulsar 函数的配置。            |
@infomagic-docs 请更新下这一行

2022-01-18 02:09 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-functionmesh/function-crd.md
> +| `FuncConfig` | 到 ConfigMap 的映射，指定 Pulsar 函数的配置。            |
updated

2022-01-18 02:41 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2022-01-18 02:41 UTC, merged