Update release-note
streamnative/snp-cn pull request #49
Opened 2022-01-21 04:25 UTC by infomagic-docs

2022-01-25 04:22 UTC, JipeiWang requested changes

2022-01-25 04:22 UTC, JipeiWang commented on v1.2.0/release-note/release-note-v1.md
> +  - [Alertmanager](/operator-guides/configure/monitoring/alertmanager.md)
这行不需要翻译
```suggestion
```

2022-01-26 05:57 UTC, infomagic-docs commented on v1.2.0/release-note/release-note-v1.md
> +  - [Alertmanager](/operator-guides/configure/monitoring/alertmanager.md)
此处只是统一了 Alertmanager 的大小写。在引用文档（https://github.com/streamnative/snp-cn/blob/master/v1.2.0/operator-guides/configure/monitoring/alertmanager.md）和 prometheus的官方文档 （https://prometheus.io/docs/alerting/latest/alertmanager/） 中，都是以 “Alertmanager” 的形式出现，而非 AlertManager

2022-02-07 09:54 UTC, tuhaihe approved these changes
@tuhaihe Approved this PR.

2022-02-07 09:54 UTC, merged