Update connector-console.md
streamnative/snp-cn pull request #50
Opened 2022-01-21 08:18 UTC by infomagic-docs

2022-01-21 08:20 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -1. From the left navigation pane, click **Connector** > **Source**.
这个 连接器 UI，在环境中没有，菜单是按文本翻译的。

2022-01-21 08:21 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   ![](../../../../image/create-source.png)
图片链接修复，下同

2022-01-21 08:21 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -* [Cloud Storage [sink](https://hub.streamnative.io/connectors/cloud-storage-sink/2.5.1) connector]([https://hub.streamnative.io/connectors/cloud-storage-sink/2.5.1](https://hub.streamnative.io/conne
原文格式错误，修复

2022-01-21 08:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -   <td>Select the tenant for the source connector.
原文错误，应该是 sink

2022-01-21 08:22 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -   <td>Select the namespace for the source connector.
原文错误，应该是 sink 吧

2022-01-25 04:35 UTC, JipeiWang approved these changes

2022-01-25 04:35 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -* [Cloud Storage [sink](https://hub.streamnative.io/connectors/cloud-storage-sink/2.5.1) connector]([https://hub.streamnative.io/connectors/cloud-storage-sink/2.5.1](https://hub.streamnative.io/conne
好的👍

2022-01-25 04:35 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> -   <td>Select the namespace for the source connector.
是的

2022-01-30 09:59 UTC, tuhaihe requested changes

2022-01-30 09:59 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 source 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
”副本“ -> 引号需要更新下。

2022-01-30 09:59 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 sink 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
”副本“ -> 引号要更新

2022-01-30 09:59 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 source 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
同上，标点更新

2022-01-30 09:59 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 sink 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
同上，标点更新

2022-02-08 06:44 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 source 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
updated

2022-02-08 06:46 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 source 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
updated

2022-02-08 06:46 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-console.md
> +   <td>启用或禁用自动扩缩。如果启用，则应该设置运行 sink 连接器的最大实例数。最大实例数必须大于”副本“的值，并且等于或小于 10。
updated

2022-02-08 07:21 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2022-02-08 07:22 UTC, merged