Update function-package.md
streamnative/snp-cn pull request #51
Opened 2022-01-21 10:02 UTC by infomagic-docs

2022-01-21 10:03 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> -        &lt;modelVersion>4.0.0&lt;/modelVersion>
代码显示错误，修复

2022-01-21 10:03 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> -1. Package your Pulsar function. For details, see [package Pulsar functions](#package-java-functions).
从链接和之后的章节看，此处原文应该是 Java function 更合适。

2022-01-21 10:04 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> -    In this example, when you write a Python Functions, you need to inherit the Function class and implement the `process()` method.
原文格式错误，正文在代码里显示了，修复。

2022-01-21 10:04 UTC, danwen1 commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> -    In this example, when you write a Python Functions, you need to inherit the Function class and implement the `process()` method.
原文格式错误，正文在代码里显示了，修复。

2022-01-25 07:58 UTC, JipeiWang requested changes

2022-01-25 07:58 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> -1. Package your Pulsar function. For details, see [package Pulsar functions](#package-java-functions).
+1，应该是 Java Functions。

2022-01-25 07:58 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +- Python 文件
这里是不是需要强调“单个 Python 文件”？

2022-01-25 07:58 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +如下示例介绍了如何使用 **Python 文件**打包 Python 函数：
同上

2022-01-25 07:58 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
```suggestion
然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数到 Pulsar 集群。
```

2022-01-26 06:12 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +- Python 文件
好的，updated

2022-01-26 06:12 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +如下示例介绍了如何使用 **Python 文件**打包 Python 函数：
Updated

2022-02-07 10:25 UTC, tuhaihe requested changes

2022-02-07 10:25 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
提交函数提交到 -> 多了一个“提交”？

2022-02-07 10:25 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
@infomagic-docs 多了一个“提交”，同上。

2022-02-07 10:25 UTC, tuhaihe commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
同样多了一个“提交”

2022-02-08 06:28 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
updated

2022-02-08 06:28 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-functions/function-package.md
> +然后，将函数 Docker 镜像推送到镜像 registry（如 [Docker Hub](https://hub.docker.com/)，或任意私有的 registry），并使用函数 Docker 镜像来配置和提交函数提交到 Pulsar 集群。
updated

2022-02-08 07:25 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2022-02-08 07:25 UTC, merged