Update connector-package.md
streamnative/snp-cn pull request #52
Opened 2022-01-21 10:08 UTC by infomagic-docs

2022-01-21 10:08 UTC, infomagic-docs commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-package.md
> -1. Package your connector to a [NAR package](#nar-package) or [JAR package](#uber-jar-package).
原文链接错误。

2022-01-25 08:02 UTC, JipeiWang requested changes

2022-01-25 08:02 UTC, JipeiWang commented on v1.2.0/user-guides/admin/work-with-connectors/connector-functionmesh/connector-package.md
> +    如下示例显示了如何使一个用名为 `pulsar-io-example.nar` 的 NAR 包定义  `Dockerfile` 。
```suggestion
    如下示例显示了如何使一个用名为 `pulsar-io-example.nar` 的 NAR 包定义 `Dockerfile` 。
```

2022-01-30 09:39 UTC, tuhaihe approved these changes
@tuhaihe Approved.

2022-01-30 09:39 UTC, merged