Wip pub sub concepts
streamnative/snp-cn pull request #7
Opened 2021-12-02 09:58 UTC by infomagic-docs

2021-12-09 15:54 UTC, tuhaihe requested changes

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +为了进行分配，命名空间被分片成 bundle 的列表，每个 bundle 包括命名空间整体哈希范围的一部分。Bundle 是属于同一命名空间的主题的虚拟组。一个命名空间 bundle 的范围在两个 32 位哈希值之间，例如从 0x00000000 到 0xffffffff。默认情况下，每个命名空间支持 4 个 bundle。
`命名空间被分片成 bundle 的列表` -> 按字面翻译没问题，事实是：命名空间被分成多个 Bundle，可优化下。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +## 派发速率
dispatch 可统一翻译为：`调度`，此种译法常见

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +`namespace`          | 主题的管理单元，将相关主题的进行分组管理。关于主题的多数配置都是在[命名空间](#命名空间)级别进行的。每个租户可以有一个或多个命名空间。
`将相关主题的进行分组管理`->优化

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +无需在 Pulsar 中特意地创建主题。如果客户端向尚不存在的主题写入消息、或者从不存在的主题接收消息，Pulsar 会在[主题名称](#主题)提供的命名空间下自动创建该主题。如果在客户端创建主题时没有指定租户或命名空间，那么该主题将在默认的租户和命名空间中创建。也可以在指定的租户和命名空间中创建一个主题，例如 `persistent://my-tenant/my-namespace/my-to
``persistent://my-tenant/my-namespace/my-topics``：更新此翻译，与原文保持一致

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +非持久化主题的消息从未在磁盘中保存，只存放在内存中。进行非持久化传输时，如果结束 Pulsar broker 或断开订阅者与主题的连接，非持久化主题的所有传输中的消息将丢失。在非持久化主题中，broker 会将消息立即发送给所有连接的订阅者，而不会在 BookKeeper 中保存。
`delivery`可更新为`分发/传递`，此说法比`传输`更常用。下同。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +因为 broker 不会持久化保存消息，非持久化消息通常比持久化消息速度更快，一旦该消息被传递给连接的 broker，就会立即向生产者返回确认信息。因此对于生产者，非持久化主题的发布延迟相对较短。
`因为 broker 不会持久化保存消息，非持久化消息通常比持久化消息速度更快，` ->可先说明结果，再说原因：`非持久化比持久化快，因为对非持久化消息来说，broker 不xxx`。如果将 `因为 broker 不会持久化保存消息` 放开头，容易让人误解 broker 不具备持久化能力。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +普通的主题仅仅是由单一 broker 提供的，这限制了该主题的最大通量。分区主题是特殊类型的主题，由多个 broker 处理，因此允许更大的通量。分区主题实际上是由 N 个内部主题实现的，其中 N 是分区的数量。当向一个分区主题发布消息时，每条消息都会被路由到多个 broker 中的一个 broker。Broker 间如何分配分区则是由 Pulsar 自动处理。
`提供`意思不妥

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +`RoundRobinPartition` | 如果没有指定 key，生产者将在所有分区中以 round-robin 方式发布消息，以达到最大通量。需要注意的是，round-robin 不作用于每条单独的消息，而是将其批处理延迟边界设置为相同，以确保批处理的有效性。而如果在消息上指定了 key，分区生产者将对 key 进行哈希运算，并将消息分配到一个特定的分区。此模式为默认模式。
`round-robin` -> `轮询（round-robin）`

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +### 排序保证
`Ordering guarantee` -> `顺序保证`，统一更新吧~

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +消息的排序与路由模式和消息的 key 相关。通常用户会希望按按键分区（Per-key-partition）保证进行排序。
`通常用户会希望按按键分区（Per-key-partition）保证进行排序。` - 重新翻译

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +如果消息上附有 key，无论是使用 `SinglePartition` 还是 `RoundRobinPartition` 模式，消息都将根据[散列 scheme](#散列-scheme)，被分配到对应的分区。
`hashing scheme`-> 目前没看到较通用翻译，可不译，如果翻译，请备注英文原句。我倾向不翻译。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +散列 scheme 是一组标准散列函数的枚举，用于为特定消息进行分区选择。
哈希函数 比 散列函数，前者说法在社区交流中更常用

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +通过死信主题，当消息不能被成功消费时，消费者仍可以去消费新的消息。在这个机制中，未能被消费的消息将被储存到一个独立的主题中，即死信主题。你可决定如何处理死信主题中的消息。
`通过死信主题，当消息不能被成功消费时，消费者仍可以去消费新的消息。` ：优化

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +死信主题依赖消息的再交付。消息重新交付的原因可以是：[确认超时](#确认超时)或[否定确认（ negative acknowledgement）](#否定确认)。如果要对消息使用否定确认，需确保在确认超时前进行否定确认。
`message re-delivery`: 消息重新分发。。请重新优化

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +死信主题依赖消息的再交付。消息重新交付的原因可以是：[确认超时](#确认超时)或[否定确认（ negative acknowledgement）](#否定确认)。如果要对消息使用否定确认，需确保在确认超时前进行否定确认。
否定确认 - 添加英文原句备注吧

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +## 重试发信主题
重试主题

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +Pulsar 具有内置 schema 注册表，客户能够为每个主题上传数据 schema。这些 schema 决定了哪些数据类型是对该主题有效的。Pulsar schema 使你能够在构建和处理消息时使用特定语言的数据类型，简单的如 `string` ，也有更复杂的特定应用类型。
`schema registry`可保持不译文，目前社区交流中多用原词。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +Pulsar 具有内置 schema 注册表，客户能够为每个主题上传数据 schema。这些 schema 决定了哪些数据类型是对该主题有效的。Pulsar schema 使你能够在构建和处理消息时使用特定语言的数据类型，简单的如 `string` ，也有更复杂的特定应用类型。
`enables clients`->客户端，不是客户...

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +延迟消息发送只在 [Shared](#shared) 订阅模式下有效。在 [Exclusive](#exclusive) 和 [Failover](#failover) 订阅模式下，延迟的消息仍会被立即发送。
Shared, Exclusive, Failover: 模式名称做下翻译吧，下面涉及的也请做同步更新。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Shared`|多个生产者可在同一个主题发布消息。 <br><br>此为**默认**设置。|
此处及下面访问模式可做翻译

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Exclusive`|仅一个生产者可在主题上发布消息。 <br><br>如果已经连接了一个生产者，则当其他生产者试图在这个主题上发表时，会立即出现错误。<br><br>如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。|
发表 -> 发布...

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Exclusive`|仅一个生产者可在主题上发布消息。 <br><br>如果已经连接了一个生产者，则当其他生产者试图在这个主题上发表时，会立即出现错误。<br><br>如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。|
`如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。` ：优化翻译

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`WaitForExclusive`|如果已经连接了一个生产者，那么这个生产者的创建将被挂起（而不是超时），直到这个生产者获得  `Exclusive`  访问权限。<br><br>成功成为独家生产者后，这个生产者将被视为领导者。如果你想为应用程序实现领导者选举方案，则可以使用这种访问模式。|
独家 -> 独占

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`WaitForExclusive`|如果已经连接了一个生产者，那么这个生产者的创建将被挂起（而不是超时），直到这个生产者获得  `Exclusive`  访问权限。<br><br>成功成为独家生产者后，这个生产者将被视为领导者。如果你想为应用程序实现领导者选举方案，则可以使用这种访问模式。|
领导者选举 -> 增加下英文原词备注。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +对于一个批处理消息，如果启用了批索引确认，broker 会保持批索引的确认状态，并跟踪每个批索引的确认状态，以避免将确认的消息发送给消费者。当该批处理消息的所有索引都被确认后，该批处理消息将被删除。
此处`batch message`可翻译为`批量消息`，下同更新

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +> - 相对于确认超时，建议优选否定确认。否定确认可以更精确地控制单个消息的再交付，在消息处理时间超过确认超时的设定时，可避免发生无效再交付。
再交付 -> 重新传递。。。下同。。。
ps，再否定确认后面备注下英文吧。

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +在 *Key_Shared*  模式下，多个消费者可以被加到同一个订阅中。消息被分发给多个消费者，有相同 key 的消息、或者有相同排序 key（orderingKey）的消息将只被交付给一个消费者。无论消息被重新交付多少次，它都只能交付给同一个消费者。当消费者进行连接或断开连接时，对于一些消息的 key，消费者将发生改变。
（orderingKey）？

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +在 *Key_Shared*  模式下，多个消费者可以被加到同一个订阅中。消息被分发给多个消费者，有相同 key 的消息、或者有相同排序 key（orderingKey）的消息将只被交付给一个消费者。无论消息被重新交付多少次，它都只能交付给同一个消费者。当消费者进行连接或断开连接时，对于一些消息的 key，消费者将发生改变。
交付 -> 传递/分发 都行，这两个常用

2021-12-09 15:54 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +> * 生产者应当禁用批处理，或使用基于 key 的批处理生成器。
同上，batch 可以翻译成 批量

2021-12-10 11:24 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +为了进行分配，命名空间被分片成 bundle 的列表，每个 bundle 包括命名空间整体哈希范围的一部分。Bundle 是属于同一命名空间的主题的虚拟组。一个命名空间 bundle 的范围在两个 32 位哈希值之间，例如从 0x00000000 到 0xffffffff。默认情况下，每个命名空间支持 4 个 bundle。
done.

2021-12-10 11:25 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +## 派发速率
done.

2021-12-10 11:25 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +`namespace`          | 主题的管理单元，将相关主题的进行分组管理。关于主题的多数配置都是在[命名空间](#命名空间)级别进行的。每个租户可以有一个或多个命名空间。
done.

2021-12-10 11:27 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +无需在 Pulsar 中特意地创建主题。如果客户端向尚不存在的主题写入消息、或者从不存在的主题接收消息，Pulsar 会在[主题名称](#主题)提供的命名空间下自动创建该主题。如果在客户端创建主题时没有指定租户或命名空间，那么该主题将在默认的租户和命名空间中创建。也可以在指定的租户和命名空间中创建一个主题，例如 `persistent://my-tenant/my-namespace/my-to
done.

2021-12-10 11:28 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +非持久化主题的消息从未在磁盘中保存，只存放在内存中。进行非持久化传输时，如果结束 Pulsar broker 或断开订阅者与主题的连接，非持久化主题的所有传输中的消息将丢失。在非持久化主题中，broker 会将消息立即发送给所有连接的订阅者，而不会在 BookKeeper 中保存。
done

2021-12-10 11:29 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +因为 broker 不会持久化保存消息，非持久化消息通常比持久化消息速度更快，一旦该消息被传递给连接的 broker，就会立即向生产者返回确认信息。因此对于生产者，非持久化主题的发布延迟相对较短。
done.

2021-12-10 11:30 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +普通的主题仅仅是由单一 broker 提供的，这限制了该主题的最大通量。分区主题是特殊类型的主题，由多个 broker 处理，因此允许更大的通量。分区主题实际上是由 N 个内部主题实现的，其中 N 是分区的数量。当向一个分区主题发布消息时，每条消息都会被路由到多个 broker 中的一个 broker。Broker 间如何分配分区则是由 Pulsar 自动处理。
done.

2021-12-10 11:32 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +`RoundRobinPartition` | 如果没有指定 key，生产者将在所有分区中以 round-robin 方式发布消息，以达到最大通量。需要注意的是，round-robin 不作用于每条单独的消息，而是将其批处理延迟边界设置为相同，以确保批处理的有效性。而如果在消息上指定了 key，分区生产者将对 key 进行哈希运算，并将消息分配到一个特定的分区。此模式为默认模式。
done.

2021-12-10 11:32 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +### 排序保证
done

2021-12-10 11:36 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +消息的排序与路由模式和消息的 key 相关。通常用户会希望按按键分区（Per-key-partition）保证进行排序。
done.

2021-12-10 11:37 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +如果消息上附有 key，无论是使用 `SinglePartition` 还是 `RoundRobinPartition` 模式，消息都将根据[散列 scheme](#散列-scheme)，被分配到对应的分区。
done.

2021-12-10 11:37 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +散列 scheme 是一组标准散列函数的枚举，用于为特定消息进行分区选择。
done.

2021-12-10 11:39 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +通过死信主题，当消息不能被成功消费时，消费者仍可以去消费新的消息。在这个机制中，未能被消费的消息将被储存到一个独立的主题中，即死信主题。你可决定如何处理死信主题中的消息。
done.

2021-12-10 11:45 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +死信主题依赖消息的再交付。消息重新交付的原因可以是：[确认超时](#确认超时)或[否定确认（ negative acknowledgement）](#否定确认)。如果要对消息使用否定确认，需确保在确认超时前进行否定确认。
done.

2021-12-10 11:45 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +## 重试发信主题
done

2021-12-10 11:47 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +Pulsar 具有内置 schema 注册表，客户能够为每个主题上传数据 schema。这些 schema 决定了哪些数据类型是对该主题有效的。Pulsar schema 使你能够在构建和处理消息时使用特定语言的数据类型，简单的如 `string` ，也有更复杂的特定应用类型。
done.

2021-12-10 11:48 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +延迟消息发送只在 [Shared](#shared) 订阅模式下有效。在 [Exclusive](#exclusive) 和 [Failover](#failover) 订阅模式下，延迟的消息仍会被立即发送。
TBD

2021-12-10 11:48 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Shared`|多个生产者可在同一个主题发布消息。 <br><br>此为**默认**设置。|
TBD

2021-12-10 11:52 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Exclusive`|仅一个生产者可在主题上发布消息。 <br><br>如果已经连接了一个生产者，则当其他生产者试图在这个主题上发表时，会立即出现错误。<br><br>如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。|
done.

2021-12-10 11:52 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`WaitForExclusive`|如果已经连接了一个生产者，那么这个生产者的创建将被挂起（而不是超时），直到这个生产者获得  `Exclusive`  访问权限。<br><br>成功成为独家生产者后，这个生产者将被视为领导者。如果你想为应用程序实现领导者选举方案，则可以使用这种访问模式。|
done.

2021-12-10 11:53 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +对于一个批处理消息，如果启用了批索引确认，broker 会保持批索引的确认状态，并跟踪每个批索引的确认状态，以避免将确认的消息发送给消费者。当该批处理消息的所有索引都被确认后，该批处理消息将被删除。
done.

2021-12-10 11:55 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +> - 相对于确认超时，建议优选否定确认。否定确认可以更精确地控制单个消息的再交付，在消息处理时间超过确认超时的设定时，可避免发生无效再交付。
done.

2021-12-10 11:57 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +在 *Key_Shared*  模式下，多个消费者可以被加到同一个订阅中。消息被分发给多个消费者，有相同 key 的消息、或者有相同排序 key（orderingKey）的消息将只被交付给一个消费者。无论消息被重新交付多少次，它都只能交付给同一个消费者。当消费者进行连接或断开连接时，对于一些消息的 key，消费者将发生改变。
done.

2021-12-10 11:57 UTC, Infomagic-ly commented on v1.2.0/concepts/pub-sub-concepts.md
> +> * 生产者应当禁用批处理，或使用基于 key 的批处理生成器。
done.

2021-12-10 13:40 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Shared`|多个生产者可在同一个主题发布消息。 <br><br>此为**默认**设置。|
done

2021-12-10 13:41 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +延迟消息发送只在 [Shared](#shared) 订阅模式下有效。在 [Exclusive](#exclusive) 和 [Failover](#failover) 订阅模式下，延迟的消息仍会被立即发送。
done

2021-12-11 03:33 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +如果消息上附有 key，无论是使用 `SinglePartition` 还是 `RoundRobinPartition` 模式，消息都将根据[散列 scheme](#散列-scheme)，被分配到对应的分区。
@Infomagic-ly 此处需要做更新

2021-12-11 03:57 UTC, tuhaihe commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Exclusive`|仅一个生产者可在主题上发布消息。 <br><br>如果已经连接了一个生产者，则当其他生产者试图在这个主题上发表时，会立即出现错误。<br><br>如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。|
`if the “old” producer experiences a network partition with the broker`
->这句新翻译忽略了网络分区，这个还得优化下 @Infomagic-ly

2021-12-11 04:53 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +如果消息上附有 key，无论是使用 `SinglePartition` 还是 `RoundRobinPartition` 模式，消息都将根据[散列 scheme](#散列-scheme)，被分配到对应的分区。
Updated.

2021-12-11 05:08 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +|`Exclusive`|仅一个生产者可在主题上发布消息。 <br><br>如果已经连接了一个生产者，则当其他生产者试图在这个主题上发表时，会立即出现错误。<br><br>如原生产者和 broker 的出现网络分区，则弃用原生产者，并选取一个新的生产者作为独家生产者。|
Updated.

2021-12-11 15:30 UTC, tuhaihe commented
@tuhaihe LGTM.

2021-12-15 15:49 UTC, JipeiWang requested changes

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +| `consumer_backlog_eviction` | Broker 开始从 backlog 丢弃积压消息。 |
```suggestion
| `consumer_backlog_eviction` | Broker 开始丢弃积压消息。 |
```

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +- 命名空间中，每个主题可允许的阈值大小
这两个项目的格式可以保持一致。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +和其他发布-订阅系统一样，Pulsar 的主题是消息从生产者传输给消费者的有命名的通道。Pulsar 支持持久化和非持久化主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。非持久性主题的数据不会保存在存储磁盘上。
“Pulsar 的主题是消息从生产者传输给消费者的有命名的通道” 可以再读起来通顺一些～

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +和其他发布-订阅系统一样，Pulsar 的主题是消息从生产者传输给消费者的有命名的通道。Pulsar 支持持久化和非持久化主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。非持久性主题的数据不会保存在存储磁盘上。
最后一句：不会持久化在存储磁盘？下一段同。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +`persistent` / `non-persistent` | 标识主题类型。Pulsar 支持持久化和[非持久化](#非持久化主题)主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。而非持久性主题的数据不会保存在存储磁盘上。
超链接的 #非持久化主题 等如果是链接下面的内容，应该是 ## 二级标题。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +按键分区（Per-key-partition）  | 具有相同 key 的消息将按顺序排列，并放置在相同的分区。 | 使用 `SinglePartition` 或 `RoundRobinPartition` 模式，且每个消息都有 key。
key的前后文翻译需统一。最后一句需重新翻译。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +散列 scheme 是一组标准散列函数的枚举，用于为特定消息进行分区选择。
```suggestion
散列 scheme 是一组标准散列函数的枚举，用于为特定消息选择分区。
```

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +Pulsar 具有内置 schema 注册表，客户能够为每个主题上传数据 schema。这些 schema 决定了哪些数据类型是对该主题有效的。Pulsar schema 使你能够在构建和处理消息时使用特定语言的数据类型，简单的如 `string` ，也有更复杂的特定应用类型。
```suggestion
Pulsar 具有内置 schema 注册表，客户能够为每个主题上传数据 schema。这些 schema 决定了哪些数据类型是对该主题有效的。Pulsar schema 使你能够在构建和处理消息时使用特定语言的数据类型，简单的如 `string`，也有更复杂的特定应用类型。
```

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +Key | 可以选择用 key 来标记消息，对主题压缩等操作有帮助。
描述需重新翻译一下

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +属性 | 用户自定义属性的键值对（可选）。
key的翻译同步

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +TypedMessageBuilder | 用来构建消息。可以通过  `TypedMessageBuilder` 来设置消息属性，如消息的 key 和赋值等。 </br> 在设置 `TypedMessageBuilder` 时，需要将 key 设置为字符串。如果把 key 设置为其他类型，如 AVRO 对象，key 就会以字节形式发送，这样就很难把 AVRO 对象发回给消费者。
```suggestion
`TypedMessageBuilder` | 用来构建消息。可以通过  `TypedMessageBuilder` 来设置消息属性，如消息的 key 和赋值等。 </br> 在设置 `TypedMessageBuilder` 时，需要将 key 设置为字符串。如果把 key 设置为其他类型，如 AVRO 对象，key 就会以字节形式发送，这样就很难把 AVRO 对象发回给消费者。 
```

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +消息的保留和过期都是在[命名空间](#命名空间)级别进行管理的。下图解释了消息保留和过期的情况。
最后一句不太通顺。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +当消息在 Pulsar 中存在一次以上时，就会出现重复消息。消息去重是 Pulsar 的一项可选功能，用于避免不必要的消息重复，即每条消息只处理一次，即使该消息被接收了不止一次。消息去重是在命名空间级别或主题级别进行处理的。
```suggestion
即每条消息只处理一次，即使该消息被接收了不止一次。消息去重是在命名空间级别或主题级别进行处理的。
```
这部分需优化

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +另一种消息去重的方式是确保每条消息*只生产一次*，这种方法通常被称为**生产者幂等**。这种方式的缺点是，它将消息去重的工作推迟到应用程序端来进行。而在 Pulsar 中，这是由 broker 来处理，无需修改 Pulsar 客户端代码，而只需要改动一下管理配置。详情请见管理消息去重。
```suggestion
这种方式的缺点是，它将消息去重的工作推迟到应用程序端来进行。而在 Pulsar 中，这是由 broker 来处理，无需修改 Pulsar 客户端代码，而只需要改动一下管理配置。详情请见管理消息去重。
```
这里想表达的应该是 Pulsar 的处理方式不同，不会有这种缺点。应该强调前一种是通常情况下

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +消息去重使得 Pulsar 成为理想的消息系统，可与流处理引擎（SPE）及其他提供有效一次（effectively-once）处理语义的系统一起使用。不提供自动消息去重的系统需要 SPE 或其他系统保证消息去重，这意味着要实现严格的消息排序，需要应用程序端来承担消息去重的任务。而使用 Pulsar，要实现严格的排序保证无需付出任何应用程序端的成本。
```suggestion
不提供自动消息去重的系统需要 SPE 或其他系统保证消息去重，这意味着要实现严格的消息排序，需要应用程序端来承担消息去重的任务。而使用 Pulsar，无需付出任何应用程序端的成本即可实现严格的排序保证。
```
同上，这部分前面需要需要突出 Pulsar 和其他系统不同，不然容易产生误解。

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +| 异步接收 | 异步接收会立即返回一个 future 值。例如 Java [`CompletableFuture`](http://www.baeldung.com/java-completablefuture)，一旦收到新消息就会完成。 |
```suggestion
例如 Java [`CompletableFuture`](http://www.baeldung.com/java-completablefuture)，一旦收到新消息就会完成。 
```
需优化

2021-12-15 15:49 UTC, JipeiWang commented on v1.2.0/concepts/pub-sub-concepts.md
> +对于一个批处理消息，如果启用了批索引确认，broker 会保持批索引的确认状态，并跟踪每个批索引的确认状态，以避免将确认的消息发送给消费者。当该批处理消息的所有索引都被确认后，该批处理消息将被删除。
批量可能引起误解，`批消息`会不会更符合语义？

2021-12-16 01:11 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +- 命名空间中，每个主题可允许的阈值大小
Updated

2021-12-16 01:13 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +和其他发布-订阅系统一样，Pulsar 的主题是消息从生产者传输给消费者的有命名的通道。Pulsar 支持持久化和非持久化主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。非持久性主题的数据不会保存在存储磁盘上。
updated

2021-12-16 01:17 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +和其他发布-订阅系统一样，Pulsar 的主题是消息从生产者传输给消费者的有命名的通道。Pulsar 支持持久化和非持久化主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。非持久性主题的数据不会保存在存储磁盘上。
updated

2021-12-16 01:19 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +`persistent` / `non-persistent` | 标识主题类型。Pulsar 支持持久化和[非持久化](#非持久化主题)主题。默认情况下，如果不指定主题类型，就会创建一个持久化主题。对于持久化主题，所有的消息都持久地保存在磁盘上（如果没有独立的 broker，消息会持久地保存在多个磁盘上）。而非持久性主题的数据不会保存在存储磁盘上。
超链接中的#不是表示标题的级数，而是 section 的 anchor

2021-12-16 01:32 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +当消息在 Pulsar 中存在一次以上时，就会出现重复消息。消息去重是 Pulsar 的一项可选功能，用于避免不必要的消息重复，即每条消息只处理一次，即使该消息被接收了不止一次。消息去重是在命名空间级别或主题级别进行处理的。
不太确定问题主要在哪个具体地方。稍微改了下表达，请review

2021-12-16 01:46 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +另一种消息去重的方式是确保每条消息*只生产一次*，这种方法通常被称为**生产者幂等**。这种方式的缺点是，它将消息去重的工作推迟到应用程序端来进行。而在 Pulsar 中，这是由 broker 来处理，无需修改 Pulsar 客户端代码，而只需要改动一下管理配置。详情请见管理消息去重。
不是非常明确comment的要求，做了一些改动。不知道有没有满足，请 reivew。

2021-12-16 01:48 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +消息去重使得 Pulsar 成为理想的消息系统，可与流处理引擎（SPE）及其他提供有效一次（effectively-once）处理语义的系统一起使用。不提供自动消息去重的系统需要 SPE 或其他系统保证消息去重，这意味着要实现严格的消息排序，需要应用程序端来承担消息去重的任务。而使用 Pulsar，要实现严格的排序保证无需付出任何应用程序端的成本。
Updated

2021-12-16 01:52 UTC, infomagic-docs commented on v1.2.0/concepts/pub-sub-concepts.md
> +| 异步接收 | 异步接收会立即返回一个 future 值。例如 Java [`CompletableFuture`](http://www.baeldung.com/java-completablefuture)，一旦收到新消息就会完成。 |
updated

2021-12-16 02:16 UTC, tuhaihe approved these changes

2021-12-16 02:16 UTC, merged