Update sn-plan.md
streamnative/snp-cn pull request #8
Opened 2021-12-06 06:44 UTC by infomagic-docs

2021-12-09 16:09 UTC, tuhaihe requested changes

2021-12-09 16:09 UTC, tuhaihe commented on v1.2.0/operator-guides/sn-plan.md
> +# Docker 注册服务器
`Docker Registry`: 不翻译，下同

2021-12-10 11:01 UTC, JipeiWang requested changes

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +本节列出了安装 StreamNative Platform 的最低要求。
```suggestion
本节列出了安装 StreamNative Platform 的基本要求。
```

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +   <td>v1.16 或更高
```suggestion
   <td>v1.16 或更高版本
```
下同

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +如果无法访问互联网，可以在安装 StreamNative Platform 之前预加载 Docker 镜像。Docker 镜像包含应用程序代码、库、工具、依赖项和其他使应用程序运行所需的文件。运行一个镜像时，它将成为一个或多个容器的实例。支持的 Docker 镜像及其下载链接，请参阅[此处](/operator-guides/operator-reference/sn-version-matri
```suggestion
如果无法访问互联网，可以在安装 StreamNative Platform 之前预加载 Docker 镜像。Docker 镜像包含应用程序代码、库、工具、依赖项和其他运行应用程序所需的文件。运行一个镜像时，它将成为一个或多个容器的实例。点击[此处](/operator-guides/operator-reference/sn-version-matrix.md)查看支持的 Docker 镜像及其下载链接。
```
可以更通顺些

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +你必须为所有 StreamNative Platform 组件提供动态持久存储。如果部署本地 Kubernetes 集群，则需要配置本地 PV 和存储类，以便将数据持久化到本地存储。详情参见[配置存储](/operator-guides/configure/storage.md)。
第一句调整一下吧

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +客户端应用程序可以通过以下不同方式，访问部署在同一个 Kubernetes 集群或不同集群中的 StreamNative Platform 组件。
```suggestion
客户端应用程序可以通过以下不同方式，访问部署在同一个或不同 Kubernetes 集群中的 StreamNative Platform 组件。
```

2021-12-10 11:01 UTC, JipeiWang commented on v1.2.0/operator-guides/sn-plan.md
> +详情参见[配置联网](/operator-guides/configure/networking.md)。
网络配置？

2021-12-10 11:15 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +# Docker 注册服务器
done.

2021-12-10 11:15 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +本节列出了安装 StreamNative Platform 的最低要求。
done.

2021-12-10 11:15 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +   <td>v1.16 或更高
done.

2021-12-10 11:17 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +如果无法访问互联网，可以在安装 StreamNative Platform 之前预加载 Docker 镜像。Docker 镜像包含应用程序代码、库、工具、依赖项和其他使应用程序运行所需的文件。运行一个镜像时，它将成为一个或多个容器的实例。支持的 Docker 镜像及其下载链接，请参阅[此处](/operator-guides/operator-reference/sn-version-matri
done.

2021-12-10 11:19 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +你必须为所有 StreamNative Platform 组件提供动态持久存储。如果部署本地 Kubernetes 集群，则需要配置本地 PV 和存储类，以便将数据持久化到本地存储。详情参见[配置存储](/operator-guides/configure/storage.md)。
必须为 StreamNative Platform 的所有组件提供动态的持久化存储。

2021-12-10 11:20 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +客户端应用程序可以通过以下不同方式，访问部署在同一个 Kubernetes 集群或不同集群中的 StreamNative Platform 组件。
done.

2021-12-10 11:20 UTC, Infomagic-ly commented on v1.2.0/operator-guides/sn-plan.md
> +详情参见[配置联网](/operator-guides/configure/networking.md)。
done.

2021-12-10 14:41 UTC, tuhaihe approved these changes
@tuhaihe LGTM.

2021-12-10 14:41 UTC, merged